// Generated by client-generator from openapi-specs/generated/bugview-api.json. Do not edit.

#[allow(unused_imports)]
pub use progenitor_client::{ByteStream, ClientInfo, Error, ResponseValue};
#[allow(unused_imports)]
use progenitor_client::{ClientHooks, OperationInfo, RequestBuilderExt, encode_path};
#[doc = r" Types used as operation parameters and responses."]
#[allow(clippy::all)]
pub mod types {
    #[doc = r" Error types."]
    pub mod error {
        #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
        pub struct ConversionError(::std::borrow::Cow<'static, str>);
        impl ::std::error::Error for ConversionError {}
        impl ::std::fmt::Display for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Display::fmt(&self.0, f)
            }
        }

        impl ::std::fmt::Debug for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }

        impl From<&'static str> for ConversionError {
            fn from(value: &'static str) -> Self {
                Self(value.into())
            }
        }

        impl From<String> for ConversionError {
            fn from(value: String) -> Self {
                Self(value.into())
            }
        }
    }

    #[doc = "Error information from a response."]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Error information from a response.\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"message\","]
    #[doc = "    \"request_id\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"error_code\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"message\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"request_id\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, schemars :: JsonSchema,
    )]
    pub struct Error {
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub error_code: ::std::option::Option<::std::string::String>,
        pub message: ::std::string::String,
        pub request_id: ::std::string::String,
    }

    impl Error {
        pub fn builder() -> builder::Error {
            Default::default()
        }
    }

    #[doc = "Full issue details (matches original Node.js bugview format)"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Full issue details (matches original Node.js bugview format)\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"fields\","]
    #[doc = "    \"id\","]
    #[doc = "    \"key\","]
    #[doc = "    \"remotelinks\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"fields\": {"]
    #[doc = "      \"description\": \"Issue fields (sanitized for public consumption)\""]
    #[doc = "    },"]
    #[doc = "    \"id\": {"]
    #[doc = "      \"description\": \"JIRA internal issue ID\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"key\": {"]
    #[doc = "      \"description\": \"Issue key (e.g., \\\"OS-1234\\\")\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"remotelinks\": {"]
    #[doc = "      \"description\": \"Remote links (filtered by allowed domains)\","]
    #[doc = "      \"type\": \"array\","]
    #[doc = "      \"items\": {"]
    #[doc = "        \"$ref\": \"#/components/schemas/RemoteLink\""]
    #[doc = "      }"]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, schemars :: JsonSchema,
    )]
    pub struct IssueDetails {
        #[doc = "Issue fields (sanitized for public consumption)"]
        pub fields: ::serde_json::Value,
        #[doc = "JIRA internal issue ID"]
        pub id: ::std::string::String,
        #[doc = "Issue key (e.g., \"OS-1234\")"]
        pub key: ::std::string::String,
        #[doc = "Remote links (filtered by allowed domains)"]
        pub remotelinks: ::std::vec::Vec<RemoteLink>,
    }

    impl IssueDetails {
        pub fn builder() -> builder::IssueDetails {
            Default::default()
        }
    }

    #[doc = "Simplified issue information for list views"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Simplified issue information for list views\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"created\","]
    #[doc = "    \"key\","]
    #[doc = "    \"status\","]
    #[doc = "    \"summary\","]
    #[doc = "    \"updated\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"created\": {"]
    #[doc = "      \"description\": \"Creation timestamp\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"key\": {"]
    #[doc = "      \"description\": \"Issue key (e.g., \\\"PROJECT-123\\\")\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"resolution\": {"]
    #[doc = "      \"description\": \"Resolution status (if resolved)\","]
    #[doc = "      \"type\": ["]
    #[doc = "        \"string\","]
    #[doc = "        \"null\""]
    #[doc = "      ]"]
    #[doc = "    },"]
    #[doc = "    \"status\": {"]
    #[doc = "      \"description\": \"Issue status (e.g., \\\"Open\\\", \\\"Resolved\\\", \\\"Closed\\\")\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"summary\": {"]
    #[doc = "      \"description\": \"Issue summary/title\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"updated\": {"]
    #[doc = "      \"description\": \"Last updated timestamp\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, schemars :: JsonSchema,
    )]
    pub struct IssueListItem {
        #[doc = "Creation timestamp"]
        pub created: ::std::string::String,
        #[doc = "Issue key (e.g., \"PROJECT-123\")"]
        pub key: ::std::string::String,
        #[doc = "Resolution status (if resolved)"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub resolution: ::std::option::Option<::std::string::String>,
        #[doc = "Issue status (e.g., \"Open\", \"Resolved\", \"Closed\")"]
        pub status: ::std::string::String,
        #[doc = "Issue summary/title"]
        pub summary: ::std::string::String,
        #[doc = "Last updated timestamp"]
        pub updated: ::std::string::String,
    }

    impl IssueListItem {
        pub fn builder() -> builder::IssueListItem {
            Default::default()
        }
    }

    #[doc = "Response for issue list endpoints"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Response for issue list endpoints\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"is_last\","]
    #[doc = "    \"issues\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"is_last\": {"]
    #[doc = "      \"description\": \"True if this is the last page\","]
    #[doc = "      \"type\": \"boolean\""]
    #[doc = "    },"]
    #[doc = "    \"issues\": {"]
    #[doc = "      \"description\": \"Issues in this page (page size determined by service configuration)\","]
    #[doc = "      \"type\": \"array\","]
    #[doc = "      \"items\": {"]
    #[doc = "        \"$ref\": \"#/components/schemas/IssueListItem\""]
    #[doc = "      }"]
    #[doc = "    },"]
    #[doc = "    \"next_page_token\": {"]
    #[doc = "      \"description\": \"Token for next page (None if this is the last page)\","]
    #[doc = "      \"type\": ["]
    #[doc = "        \"string\","]
    #[doc = "        \"null\""]
    #[doc = "      ]"]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, schemars :: JsonSchema,
    )]
    pub struct IssueListResponse {
        #[doc = "True if this is the last page"]
        pub is_last: bool,
        #[doc = "Issues in this page (page size determined by service configuration)"]
        pub issues: ::std::vec::Vec<IssueListItem>,
        #[doc = "Token for next page (None if this is the last page)"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub next_page_token: ::std::option::Option<::std::string::String>,
    }

    impl IssueListResponse {
        pub fn builder() -> builder::IssueListResponse {
            Default::default()
        }
    }

    #[doc = "Sort field for issue lists"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Sort field for issue lists\","]
    #[doc = "  \"oneOf\": ["]
    #[doc = "    {"]
    #[doc = "      \"description\": \"Sort by issue key (e.g., OS-1234)\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"enum\": ["]
    #[doc = "        \"key\""]
    #[doc = "      ]"]
    #[doc = "    },"]
    #[doc = "    {"]
    #[doc = "      \"description\": \"Sort by creation date\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"enum\": ["]
    #[doc = "        \"created\""]
    #[doc = "      ]"]
    #[doc = "    },"]
    #[doc = "    {"]
    #[doc = "      \"description\": \"Sort by last update date (default)\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"enum\": ["]
    #[doc = "        \"updated\""]
    #[doc = "      ]"]
    #[doc = "    }"]
    #[doc = "  ]"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize,
        :: serde :: Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
        clap :: ValueEnum,
        schemars :: JsonSchema,
    )]
    pub enum IssueSort {
        #[doc = "Sort by issue key (e.g., OS-1234)"]
        #[serde(rename = "key")]
        Key,
        #[doc = "Sort by creation date"]
        #[serde(rename = "created")]
        Created,
        #[doc = "Sort by last update date (default)"]
        #[serde(rename = "updated")]
        Updated,
    }

    impl ::std::fmt::Display for IssueSort {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Key => f.write_str("key"),
                Self::Created => f.write_str("created"),
                Self::Updated => f.write_str("updated"),
            }
        }
    }

    impl ::std::str::FromStr for IssueSort {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "key" => Ok(Self::Key),
                "created" => Ok(Self::Created),
                "updated" => Ok(Self::Updated),
                _ => Err("invalid value".into()),
            }
        }
    }

    impl ::std::convert::TryFrom<&str> for IssueSort {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }

    impl ::std::convert::TryFrom<&::std::string::String> for IssueSort {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }

    impl ::std::convert::TryFrom<::std::string::String> for IssueSort {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }

    #[doc = "Legacy issue summary format (for backwards compatibility with Node.js bugview)\n\nThis matches the original `/bugview/json/{key}` response format."]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Legacy issue summary format (for backwards compatibility with Node.js bugview)\\n\\nThis matches the original `/bugview/json/{key}` response format.\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"id\","]
    #[doc = "    \"summary\","]
    #[doc = "    \"web_url\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"id\": {"]
    #[doc = "      \"description\": \"Issue key (named \\\"id\\\" for legacy compatibility)\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"summary\": {"]
    #[doc = "      \"description\": \"Issue summary/title\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"web_url\": {"]
    #[doc = "      \"description\": \"URL to the bugview web page for this issue\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, schemars :: JsonSchema,
    )]
    pub struct IssueSummary {
        #[doc = "Issue key (named \"id\" for legacy compatibility)"]
        pub id: ::std::string::String,
        #[doc = "Issue summary/title"]
        pub summary: ::std::string::String,
        #[doc = "URL to the bugview web page for this issue"]
        pub web_url: ::std::string::String,
    }

    impl IssueSummary {
        pub fn builder() -> builder::IssueSummary {
            Default::default()
        }
    }

    #[doc = "Remote link information"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Remote link information\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"title\","]
    #[doc = "    \"url\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"title\": {"]
    #[doc = "      \"description\": \"Link title/description\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"url\": {"]
    #[doc = "      \"description\": \"Link URL\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, schemars :: JsonSchema,
    )]
    pub struct RemoteLink {
        #[doc = "Link title/description"]
        pub title: ::std::string::String,
        #[doc = "Link URL"]
        pub url: ::std::string::String,
    }

    impl RemoteLink {
        pub fn builder() -> builder::RemoteLink {
            Default::default()
        }
    }

    #[doc = r" Types for composing complex structures."]
    pub mod builder {
        #[derive(Clone, Debug)]
        pub struct Error {
            error_code: ::std::result::Result<
                ::std::option::Option<::std::string::String>,
                ::std::string::String,
            >,
            message: ::std::result::Result<::std::string::String, ::std::string::String>,
            request_id: ::std::result::Result<::std::string::String, ::std::string::String>,
        }

        impl ::std::default::Default for Error {
            fn default() -> Self {
                Self {
                    error_code: Ok(Default::default()),
                    message: Err("no value supplied for message".to_string()),
                    request_id: Err("no value supplied for request_id".to_string()),
                }
            }
        }

        impl Error {
            pub fn error_code<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::option::Option<::std::string::String>>,
                T::Error: ::std::fmt::Display,
            {
                self.error_code = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for error_code: {e}"));
                self
            }
            pub fn message<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.message = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for message: {e}"));
                self
            }
            pub fn request_id<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.request_id = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for request_id: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<Error> for super::Error {
            type Error = super::error::ConversionError;
            fn try_from(
                value: Error,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    error_code: value.error_code?,
                    message: value.message?,
                    request_id: value.request_id?,
                })
            }
        }

        impl ::std::convert::From<super::Error> for Error {
            fn from(value: super::Error) -> Self {
                Self {
                    error_code: Ok(value.error_code),
                    message: Ok(value.message),
                    request_id: Ok(value.request_id),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct IssueDetails {
            fields: ::std::result::Result<::serde_json::Value, ::std::string::String>,
            id: ::std::result::Result<::std::string::String, ::std::string::String>,
            key: ::std::result::Result<::std::string::String, ::std::string::String>,
            remotelinks:
                ::std::result::Result<::std::vec::Vec<super::RemoteLink>, ::std::string::String>,
        }

        impl ::std::default::Default for IssueDetails {
            fn default() -> Self {
                Self {
                    fields: Err("no value supplied for fields".to_string()),
                    id: Err("no value supplied for id".to_string()),
                    key: Err("no value supplied for key".to_string()),
                    remotelinks: Err("no value supplied for remotelinks".to_string()),
                }
            }
        }

        impl IssueDetails {
            pub fn fields<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::serde_json::Value>,
                T::Error: ::std::fmt::Display,
            {
                self.fields = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for fields: {e}"));
                self
            }
            pub fn id<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.id = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for id: {e}"));
                self
            }
            pub fn key<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.key = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for key: {e}"));
                self
            }
            pub fn remotelinks<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::vec::Vec<super::RemoteLink>>,
                T::Error: ::std::fmt::Display,
            {
                self.remotelinks = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for remotelinks: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<IssueDetails> for super::IssueDetails {
            type Error = super::error::ConversionError;
            fn try_from(
                value: IssueDetails,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    fields: value.fields?,
                    id: value.id?,
                    key: value.key?,
                    remotelinks: value.remotelinks?,
                })
            }
        }

        impl ::std::convert::From<super::IssueDetails> for IssueDetails {
            fn from(value: super::IssueDetails) -> Self {
                Self {
                    fields: Ok(value.fields),
                    id: Ok(value.id),
                    key: Ok(value.key),
                    remotelinks: Ok(value.remotelinks),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct IssueListItem {
            created: ::std::result::Result<::std::string::String, ::std::string::String>,
            key: ::std::result::Result<::std::string::String, ::std::string::String>,
            resolution: ::std::result::Result<
                ::std::option::Option<::std::string::String>,
                ::std::string::String,
            >,
            status: ::std::result::Result<::std::string::String, ::std::string::String>,
            summary: ::std::result::Result<::std::string::String, ::std::string::String>,
            updated: ::std::result::Result<::std::string::String, ::std::string::String>,
        }

        impl ::std::default::Default for IssueListItem {
            fn default() -> Self {
                Self {
                    created: Err("no value supplied for created".to_string()),
                    key: Err("no value supplied for key".to_string()),
                    resolution: Ok(Default::default()),
                    status: Err("no value supplied for status".to_string()),
                    summary: Err("no value supplied for summary".to_string()),
                    updated: Err("no value supplied for updated".to_string()),
                }
            }
        }

        impl IssueListItem {
            pub fn created<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.created = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for created: {e}"));
                self
            }
            pub fn key<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.key = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for key: {e}"));
                self
            }
            pub fn resolution<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::option::Option<::std::string::String>>,
                T::Error: ::std::fmt::Display,
            {
                self.resolution = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for resolution: {e}"));
                self
            }
            pub fn status<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.status = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for status: {e}"));
                self
            }
            pub fn summary<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.summary = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for summary: {e}"));
                self
            }
            pub fn updated<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.updated = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for updated: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<IssueListItem> for super::IssueListItem {
            type Error = super::error::ConversionError;
            fn try_from(
                value: IssueListItem,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    created: value.created?,
                    key: value.key?,
                    resolution: value.resolution?,
                    status: value.status?,
                    summary: value.summary?,
                    updated: value.updated?,
                })
            }
        }

        impl ::std::convert::From<super::IssueListItem> for IssueListItem {
            fn from(value: super::IssueListItem) -> Self {
                Self {
                    created: Ok(value.created),
                    key: Ok(value.key),
                    resolution: Ok(value.resolution),
                    status: Ok(value.status),
                    summary: Ok(value.summary),
                    updated: Ok(value.updated),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct IssueListResponse {
            is_last: ::std::result::Result<bool, ::std::string::String>,
            issues:
                ::std::result::Result<::std::vec::Vec<super::IssueListItem>, ::std::string::String>,
            next_page_token: ::std::result::Result<
                ::std::option::Option<::std::string::String>,
                ::std::string::String,
            >,
        }

        impl ::std::default::Default for IssueListResponse {
            fn default() -> Self {
                Self {
                    is_last: Err("no value supplied for is_last".to_string()),
                    issues: Err("no value supplied for issues".to_string()),
                    next_page_token: Ok(Default::default()),
                }
            }
        }

        impl IssueListResponse {
            pub fn is_last<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<bool>,
                T::Error: ::std::fmt::Display,
            {
                self.is_last = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for is_last: {e}"));
                self
            }
            pub fn issues<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::vec::Vec<super::IssueListItem>>,
                T::Error: ::std::fmt::Display,
            {
                self.issues = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for issues: {e}"));
                self
            }
            pub fn next_page_token<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::option::Option<::std::string::String>>,
                T::Error: ::std::fmt::Display,
            {
                self.next_page_token = value.try_into().map_err(|e| {
                    format!("error converting supplied value for next_page_token: {e}")
                });
                self
            }
        }

        impl ::std::convert::TryFrom<IssueListResponse> for super::IssueListResponse {
            type Error = super::error::ConversionError;
            fn try_from(
                value: IssueListResponse,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    is_last: value.is_last?,
                    issues: value.issues?,
                    next_page_token: value.next_page_token?,
                })
            }
        }

        impl ::std::convert::From<super::IssueListResponse> for IssueListResponse {
            fn from(value: super::IssueListResponse) -> Self {
                Self {
                    is_last: Ok(value.is_last),
                    issues: Ok(value.issues),
                    next_page_token: Ok(value.next_page_token),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct IssueSummary {
            id: ::std::result::Result<::std::string::String, ::std::string::String>,
            summary: ::std::result::Result<::std::string::String, ::std::string::String>,
            web_url: ::std::result::Result<::std::string::String, ::std::string::String>,
        }

        impl ::std::default::Default for IssueSummary {
            fn default() -> Self {
                Self {
                    id: Err("no value supplied for id".to_string()),
                    summary: Err("no value supplied for summary".to_string()),
                    web_url: Err("no value supplied for web_url".to_string()),
                }
            }
        }

        impl IssueSummary {
            pub fn id<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.id = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for id: {e}"));
                self
            }
            pub fn summary<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.summary = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for summary: {e}"));
                self
            }
            pub fn web_url<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.web_url = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for web_url: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<IssueSummary> for super::IssueSummary {
            type Error = super::error::ConversionError;
            fn try_from(
                value: IssueSummary,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    id: value.id?,
                    summary: value.summary?,
                    web_url: value.web_url?,
                })
            }
        }

        impl ::std::convert::From<super::IssueSummary> for IssueSummary {
            fn from(value: super::IssueSummary) -> Self {
                Self {
                    id: Ok(value.id),
                    summary: Ok(value.summary),
                    web_url: Ok(value.web_url),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct RemoteLink {
            title: ::std::result::Result<::std::string::String, ::std::string::String>,
            url: ::std::result::Result<::std::string::String, ::std::string::String>,
        }

        impl ::std::default::Default for RemoteLink {
            fn default() -> Self {
                Self {
                    title: Err("no value supplied for title".to_string()),
                    url: Err("no value supplied for url".to_string()),
                }
            }
        }

        impl RemoteLink {
            pub fn title<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.title = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for title: {e}"));
                self
            }
            pub fn url<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.url = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for url: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<RemoteLink> for super::RemoteLink {
            type Error = super::error::ConversionError;
            fn try_from(
                value: RemoteLink,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    title: value.title?,
                    url: value.url?,
                })
            }
        }

        impl ::std::convert::From<super::RemoteLink> for RemoteLink {
            fn from(value: super::RemoteLink) -> Self {
                Self {
                    title: Ok(value.title),
                    url: Ok(value.url),
                }
            }
        }
    }
}

#[derive(Clone, Debug)]
#[doc = "Client for Bugview API\n\nPublic JIRA issue viewer API\n\nVersion: 0.1.0"]
pub struct Client {
    pub(crate) baseurl: String,
    pub(crate) client: reqwest::Client,
}

impl Client {
    #[doc = r" Create a new client."]
    #[doc = r""]
    #[doc = r" `baseurl` is the base URL provided to the internal"]
    #[doc = r" `reqwest::Client`, and should include a scheme and hostname,"]
    #[doc = r" as well as port and a path stem if applicable."]
    pub fn new(baseurl: &str) -> Self {
        #[cfg(not(target_arch = "wasm32"))]
        let client = {
            let dur = ::std::time::Duration::from_secs(15u64);
            reqwest::ClientBuilder::new()
                .connect_timeout(dur)
                .timeout(dur)
        };
        #[cfg(target_arch = "wasm32")]
        let client = reqwest::ClientBuilder::new();
        Self::new_with_client(baseurl, client.build().unwrap())
    }

    #[doc = r" Construct a new client with an existing `reqwest::Client`,"]
    #[doc = r" allowing more control over its configuration."]
    #[doc = r""]
    #[doc = r" `baseurl` is the base URL provided to the internal"]
    #[doc = r" `reqwest::Client`, and should include a scheme and hostname,"]
    #[doc = r" as well as port and a path stem if applicable."]
    pub fn new_with_client(baseurl: &str, client: reqwest::Client) -> Self {
        Self {
            baseurl: baseurl.to_string(),
            client,
        }
    }
}

impl ClientInfo<()> for Client {
    fn api_version() -> &'static str {
        "0.1.0"
    }

    fn baseurl(&self) -> &str {
        self.baseurl.as_str()
    }

    fn client(&self) -> &reqwest::Client {
        &self.client
    }

    fn inner(&self) -> &() {
        &()
    }
}

impl ClientHooks<()> for &Client {}
impl Client {
    #[doc = "Redirect /bugview to /bugview/index.html\n\nSends a `GET` request to `/bugview`\n\n```ignore\nlet response = client.redirect_bugview_root()\n    .send()\n    .await;\n```"]
    pub fn redirect_bugview_root(&self) -> builder::RedirectBugviewRoot<'_> {
        builder::RedirectBugviewRoot::new(self)
    }

    #[doc = "Get full issue details as JSON\n\nReturns complete issue information including all fields.\n\nSends a `GET` request to `/bugview/fulljson/{key}`\n\nArguments:\n- `key`: Issue key (e.g., \"PROJECT-123\")\n```ignore\nlet response = client.get_issue_full_json()\n    .key(key)\n    .send()\n    .await;\n```"]
    pub fn get_issue_full_json(&self) -> builder::GetIssueFullJson<'_> {
        builder::GetIssueFullJson::new(self)
    }

    #[doc = "Get issue index as HTML\n\nReturns a paginated HTML view of public issues.\n\nSends a `GET` request to `/bugview/index.html`\n\nArguments:\n- `next_page_token`: Next page token for pagination (token-based, not offset)\n- `sort`: Sort field (key, created, or updated). Defaults to \"updated\" if omitted.\n```ignore\nlet response = client.get_issue_index_html()\n    .next_page_token(next_page_token)\n    .sort(sort)\n    .send()\n    .await;\n```"]
    pub fn get_issue_index_html(&self) -> builder::GetIssueIndexHtml<'_> {
        builder::GetIssueIndexHtml::new(self)
    }

    #[doc = "Get issue index as JSON\n\nReturns a paginated list of public issues.\n\nSends a `GET` request to `/bugview/index.json`\n\nArguments:\n- `next_page_token`: Next page token for pagination (token-based, not offset)\n- `sort`: Sort field (key, created, or updated). Defaults to \"updated\" if omitted.\n```ignore\nlet response = client.get_issue_index_json()\n    .next_page_token(next_page_token)\n    .sort(sort)\n    .send()\n    .await;\n```"]
    pub fn get_issue_index_json(&self) -> builder::GetIssueIndexJson<'_> {
        builder::GetIssueIndexJson::new(self)
    }

    #[doc = "Get issue details as HTML\n\nReturns an HTML view of a single issue with full details.\n\nSends a `GET` request to `/bugview/issue/{key}`\n\nArguments:\n- `key`: Issue key (e.g., \"PROJECT-123\")\n```ignore\nlet response = client.get_issue_html()\n    .key(key)\n    .send()\n    .await;\n```"]
    pub fn get_issue_html(&self) -> builder::GetIssueHtml<'_> {
        builder::GetIssueHtml::new(self)
    }

    #[doc = "Get issue summary as JSON (legacy format)\n\nReturns issue key, summary, and web URL. This endpoint maintains backwards compatibility with the original Node.js bugview service.\n\nSends a `GET` request to `/bugview/json/{key}`\n\nArguments:\n- `key`: Issue key (e.g., \"PROJECT-123\")\n```ignore\nlet response = client.get_issue_json()\n    .key(key)\n    .send()\n    .await;\n```"]
    pub fn get_issue_json(&self) -> builder::GetIssueJson<'_> {
        builder::GetIssueJson::new(self)
    }

    #[doc = "Get issues for a specific label as HTML\n\nReturns a paginated HTML view of issues with the specified label.\n\nSends a `GET` request to `/bugview/label/{key}`\n\nArguments:\n- `key`: Label key\n- `next_page_token`: Next page token for pagination (token-based, not offset)\n- `sort`: Sort field (key, created, or updated). Defaults to \"updated\" if omitted.\n```ignore\nlet response = client.get_label_index_html()\n    .key(key)\n    .next_page_token(next_page_token)\n    .sort(sort)\n    .send()\n    .await;\n```"]
    pub fn get_label_index_html(&self) -> builder::GetLabelIndexHtml<'_> {
        builder::GetLabelIndexHtml::new(self)
    }
}

#[doc = r" Types for composing operation parameters."]
#[allow(clippy::all)]
pub mod builder {
    use super::types;
    #[allow(unused_imports)]
    use super::{
        ByteStream, ClientHooks, ClientInfo, Error, OperationInfo, RequestBuilderExt,
        ResponseValue, encode_path,
    };
    #[doc = "Builder for [`Client::redirect_bugview_root`]\n\n[`Client::redirect_bugview_root`]: super::Client::redirect_bugview_root"]
    #[derive(Debug, Clone)]
    pub struct RedirectBugviewRoot<'a> {
        client: &'a super::Client,
    }

    impl<'a> RedirectBugviewRoot<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self { client: client }
        }

        #[doc = "Sends a `GET` request to `/bugview`"]
        pub async fn send(self) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
            let Self { client } = self;
            let url = format!("{}/bugview", client.baseurl,);
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client.client.get(url).headers(header_map).build()?;
            let info = OperationInfo {
                operation_id: "redirect_bugview_root",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200..=299 => Ok(ResponseValue::stream(response)),
                _ => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            }
        }
    }

    #[doc = "Builder for [`Client::get_issue_full_json`]\n\n[`Client::get_issue_full_json`]: super::Client::get_issue_full_json"]
    #[derive(Debug, Clone)]
    pub struct GetIssueFullJson<'a> {
        client: &'a super::Client,
        key: Result<::std::string::String, String>,
    }

    impl<'a> GetIssueFullJson<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self {
                client: client,
                key: Err("key was not initialized".to_string()),
            }
        }

        pub fn key<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.key = value.try_into().map_err(|_| {
                "conversion to `:: std :: string :: String` for key failed".to_string()
            });
            self
        }

        #[doc = "Sends a `GET` request to `/bugview/fulljson/{key}`"]
        pub async fn send(self) -> Result<ResponseValue<types::IssueDetails>, Error<types::Error>> {
            let Self { client, key } = self;
            let key = key.map_err(Error::InvalidRequest)?;
            let url = format!(
                "{}/bugview/fulljson/{}",
                client.baseurl,
                encode_path(&key.to_string()),
            );
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .get(url)
                .header(
                    ::reqwest::header::ACCEPT,
                    ::reqwest::header::HeaderValue::from_static("application/json"),
                )
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "get_issue_full_json",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200u16 => ResponseValue::from_response(response).await,
                400u16..=499u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                500u16..=599u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                _ => Err(Error::UnexpectedResponse(response)),
            }
        }
    }

    #[doc = "Builder for [`Client::get_issue_index_html`]\n\n[`Client::get_issue_index_html`]: super::Client::get_issue_index_html"]
    #[derive(Debug, Clone)]
    pub struct GetIssueIndexHtml<'a> {
        client: &'a super::Client,
        next_page_token: Result<Option<::std::string::String>, String>,
        sort: Result<Option<types::IssueSort>, String>,
    }

    impl<'a> GetIssueIndexHtml<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self {
                client: client,
                next_page_token: Ok(None),
                sort: Ok(None),
            }
        }

        pub fn next_page_token<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.next_page_token = value.try_into().map(Some).map_err(|_| {
                "conversion to `:: std :: string :: String` for next_page_token failed".to_string()
            });
            self
        }

        pub fn sort<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<types::IssueSort>,
        {
            self.sort = value
                .try_into()
                .map(Some)
                .map_err(|_| "conversion to `IssueSort` for sort failed".to_string());
            self
        }

        #[doc = "Sends a `GET` request to `/bugview/index.html`"]
        pub async fn send(self) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
            let Self {
                client,
                next_page_token,
                sort,
            } = self;
            let next_page_token = next_page_token.map_err(Error::InvalidRequest)?;
            let sort = sort.map_err(Error::InvalidRequest)?;
            let url = format!("{}/bugview/index.html", client.baseurl,);
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .get(url)
                .query(&progenitor_client::QueryParam::new(
                    "next_page_token",
                    &next_page_token,
                ))
                .query(&progenitor_client::QueryParam::new("sort", &sort))
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "get_issue_index_html",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200..=299 => Ok(ResponseValue::stream(response)),
                _ => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            }
        }
    }

    #[doc = "Builder for [`Client::get_issue_index_json`]\n\n[`Client::get_issue_index_json`]: super::Client::get_issue_index_json"]
    #[derive(Debug, Clone)]
    pub struct GetIssueIndexJson<'a> {
        client: &'a super::Client,
        next_page_token: Result<Option<::std::string::String>, String>,
        sort: Result<Option<types::IssueSort>, String>,
    }

    impl<'a> GetIssueIndexJson<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self {
                client: client,
                next_page_token: Ok(None),
                sort: Ok(None),
            }
        }

        pub fn next_page_token<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.next_page_token = value.try_into().map(Some).map_err(|_| {
                "conversion to `:: std :: string :: String` for next_page_token failed".to_string()
            });
            self
        }

        pub fn sort<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<types::IssueSort>,
        {
            self.sort = value
                .try_into()
                .map(Some)
                .map_err(|_| "conversion to `IssueSort` for sort failed".to_string());
            self
        }

        #[doc = "Sends a `GET` request to `/bugview/index.json`"]
        pub async fn send(
            self,
        ) -> Result<ResponseValue<types::IssueListResponse>, Error<types::Error>> {
            let Self {
                client,
                next_page_token,
                sort,
            } = self;
            let next_page_token = next_page_token.map_err(Error::InvalidRequest)?;
            let sort = sort.map_err(Error::InvalidRequest)?;
            let url = format!("{}/bugview/index.json", client.baseurl,);
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .get(url)
                .header(
                    ::reqwest::header::ACCEPT,
                    ::reqwest::header::HeaderValue::from_static("application/json"),
                )
                .query(&progenitor_client::QueryParam::new(
                    "next_page_token",
                    &next_page_token,
                ))
                .query(&progenitor_client::QueryParam::new("sort", &sort))
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "get_issue_index_json",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200u16 => ResponseValue::from_response(response).await,
                400u16..=499u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                500u16..=599u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                _ => Err(Error::UnexpectedResponse(response)),
            }
        }
    }

    #[doc = "Builder for [`Client::get_issue_html`]\n\n[`Client::get_issue_html`]: super::Client::get_issue_html"]
    #[derive(Debug, Clone)]
    pub struct GetIssueHtml<'a> {
        client: &'a super::Client,
        key: Result<::std::string::String, String>,
    }

    impl<'a> GetIssueHtml<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self {
                client: client,
                key: Err("key was not initialized".to_string()),
            }
        }

        pub fn key<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.key = value.try_into().map_err(|_| {
                "conversion to `:: std :: string :: String` for key failed".to_string()
            });
            self
        }

        #[doc = "Sends a `GET` request to `/bugview/issue/{key}`"]
        pub async fn send(self) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
            let Self { client, key } = self;
            let key = key.map_err(Error::InvalidRequest)?;
            let url = format!(
                "{}/bugview/issue/{}",
                client.baseurl,
                encode_path(&key.to_string()),
            );
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client.client.get(url).headers(header_map).build()?;
            let info = OperationInfo {
                operation_id: "get_issue_html",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200..=299 => Ok(ResponseValue::stream(response)),
                _ => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            }
        }
    }

    #[doc = "Builder for [`Client::get_issue_json`]\n\n[`Client::get_issue_json`]: super::Client::get_issue_json"]
    #[derive(Debug, Clone)]
    pub struct GetIssueJson<'a> {
        client: &'a super::Client,
        key: Result<::std::string::String, String>,
    }

    impl<'a> GetIssueJson<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self {
                client: client,
                key: Err("key was not initialized".to_string()),
            }
        }

        pub fn key<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.key = value.try_into().map_err(|_| {
                "conversion to `:: std :: string :: String` for key failed".to_string()
            });
            self
        }

        #[doc = "Sends a `GET` request to `/bugview/json/{key}`"]
        pub async fn send(self) -> Result<ResponseValue<types::IssueSummary>, Error<types::Error>> {
            let Self { client, key } = self;
            let key = key.map_err(Error::InvalidRequest)?;
            let url = format!(
                "{}/bugview/json/{}",
                client.baseurl,
                encode_path(&key.to_string()),
            );
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .get(url)
                .header(
                    ::reqwest::header::ACCEPT,
                    ::reqwest::header::HeaderValue::from_static("application/json"),
                )
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "get_issue_json",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200u16 => ResponseValue::from_response(response).await,
                400u16..=499u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                500u16..=599u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                _ => Err(Error::UnexpectedResponse(response)),
            }
        }
    }

    #[doc = "Builder for [`Client::get_label_index_html`]\n\n[`Client::get_label_index_html`]: super::Client::get_label_index_html"]
    #[derive(Debug, Clone)]
    pub struct GetLabelIndexHtml<'a> {
        client: &'a super::Client,
        key: Result<::std::string::String, String>,
        next_page_token: Result<Option<::std::string::String>, String>,
        sort: Result<Option<types::IssueSort>, String>,
    }

    impl<'a> GetLabelIndexHtml<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self {
                client: client,
                key: Err("key was not initialized".to_string()),
                next_page_token: Ok(None),
                sort: Ok(None),
            }
        }

        pub fn key<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.key = value.try_into().map_err(|_| {
                "conversion to `:: std :: string :: String` for key failed".to_string()
            });
            self
        }

        pub fn next_page_token<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.next_page_token = value.try_into().map(Some).map_err(|_| {
                "conversion to `:: std :: string :: String` for next_page_token failed".to_string()
            });
            self
        }

        pub fn sort<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<types::IssueSort>,
        {
            self.sort = value
                .try_into()
                .map(Some)
                .map_err(|_| "conversion to `IssueSort` for sort failed".to_string());
            self
        }

        #[doc = "Sends a `GET` request to `/bugview/label/{key}`"]
        pub async fn send(self) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
            let Self {
                client,
                key,
                next_page_token,
                sort,
            } = self;
            let key = key.map_err(Error::InvalidRequest)?;
            let next_page_token = next_page_token.map_err(Error::InvalidRequest)?;
            let sort = sort.map_err(Error::InvalidRequest)?;
            let url = format!(
                "{}/bugview/label/{}",
                client.baseurl,
                encode_path(&key.to_string()),
            );
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .get(url)
                .query(&progenitor_client::QueryParam::new(
                    "next_page_token",
                    &next_page_token,
                ))
                .query(&progenitor_client::QueryParam::new("sort", &sort))
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "get_label_index_html",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200..=299 => Ok(ResponseValue::stream(response)),
                _ => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            }
        }
    }
}

#[doc = r" Items consumers will typically use such as the Client."]
pub mod prelude {
    pub use self::super::Client;
}
