// Generated by client-generator from openapi-specs/generated/jira-api.json. Do not edit.

#[allow(unused_imports)]
use progenitor_client::{encode_path, ClientHooks, OperationInfo, RequestBuilderExt};
#[allow(unused_imports)]
pub use progenitor_client::{ByteStream, ClientInfo, Error, ResponseValue};
#[doc = r" Types used as operation parameters and responses."]
#[allow(clippy::all)]
pub mod types {
    #[doc = r" Error types."]
    pub mod error {
        #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
        pub struct ConversionError(::std::borrow::Cow<'static, str>);
        impl ::std::error::Error for ConversionError {}
        impl ::std::fmt::Display for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Display::fmt(&self.0, f)
            }
        }

        impl ::std::fmt::Debug for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }

        impl From<&'static str> for ConversionError {
            fn from(value: &'static str) -> Self {
                Self(value.into())
            }
        }

        impl From<String> for ConversionError {
            fn from(value: String) -> Self {
                Self(value.into())
            }
        }
    }

    #[doc = "Error information from a response."]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Error information from a response.\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"message\","]
    #[doc = "    \"request_id\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"error_code\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"message\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"request_id\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct Error {
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub error_code: ::std::option::Option<::std::string::String>,
        pub message: ::std::string::String,
        pub request_id: ::std::string::String,
    }

    impl Error {
        pub fn builder() -> builder::Error {
            Default::default()
        }
    }

    #[doc = "Full issue details"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Full issue details\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"fields\","]
    #[doc = "    \"id\","]
    #[doc = "    \"key\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"fields\": {"]
    #[doc = "      \"description\": \"Issue fields as a dynamic JSON object\","]
    #[doc = "      \"type\": \"object\","]
    #[doc = "      \"additionalProperties\": true"]
    #[doc = "    },"]
    #[doc = "    \"id\": {"]
    #[doc = "      \"description\": \"Issue ID (numeric)\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"key\": {"]
    #[doc = "      \"description\": \"Issue key (e.g., \\\"PROJECT-123\\\")\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"renderedFields\": {"]
    #[doc = "      \"description\": \"Rendered (HTML) versions of fields when expand=renderedFields is used\","]
    #[doc = "      \"type\": ["]
    #[doc = "        \"object\","]
    #[doc = "        \"null\""]
    #[doc = "      ],"]
    #[doc = "      \"additionalProperties\": true"]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct Issue {
        #[doc = "Issue fields as a dynamic JSON object"]
        pub fields: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
        #[doc = "Issue ID (numeric)"]
        pub id: ::std::string::String,
        #[doc = "Issue key (e.g., \"PROJECT-123\")"]
        pub key: ::std::string::String,
        #[doc = "Rendered (HTML) versions of fields when expand=renderedFields is used"]
        #[serde(
            rename = "renderedFields",
            default,
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub rendered_fields:
            ::std::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }

    impl Issue {
        pub fn builder() -> builder::Issue {
            Default::default()
        }
    }

    #[doc = "Remote link information"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Remote link information\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"id\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"id\": {"]
    #[doc = "      \"description\": \"Remote link ID\","]
    #[doc = "      \"type\": \"integer\","]
    #[doc = "      \"format\": \"uint64\","]
    #[doc = "      \"minimum\": 0.0"]
    #[doc = "    },"]
    #[doc = "    \"object\": {"]
    #[doc = "      \"description\": \"Remote link object with URL and title\","]
    #[doc = "      \"oneOf\": ["]
    #[doc = "        {"]
    #[doc = "          \"type\": \"null\""]
    #[doc = "        },"]
    #[doc = "        {"]
    #[doc = "          \"allOf\": ["]
    #[doc = "            {"]
    #[doc = "              \"$ref\": \"#/components/schemas/RemoteLinkObject\""]
    #[doc = "            }"]
    #[doc = "          ]"]
    #[doc = "        }"]
    #[doc = "      ]"]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct RemoteLink {
        #[doc = "Remote link ID"]
        pub id: u64,
        #[doc = "Remote link object with URL and title"]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub object: ::std::option::Option<RemoteLinkObject>,
    }

    impl RemoteLink {
        pub fn builder() -> builder::RemoteLink {
            Default::default()
        }
    }

    #[doc = "Remote link object details"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Remote link object details\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"title\","]
    #[doc = "    \"url\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"title\": {"]
    #[doc = "      \"description\": \"Title/description of the remote resource\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"url\": {"]
    #[doc = "      \"description\": \"URL of the remote resource\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct RemoteLinkObject {
        #[doc = "Title/description of the remote resource"]
        pub title: ::std::string::String,
        #[doc = "URL of the remote resource"]
        pub url: ::std::string::String,
    }

    impl RemoteLinkObject {
        pub fn builder() -> builder::RemoteLinkObject {
            Default::default()
        }
    }

    #[doc = "Response from JIRA search endpoint"]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Response from JIRA search endpoint\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"issues\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"isLast\": {"]
    #[doc = "      \"description\": \"Whether this is the last page of results\","]
    #[doc = "      \"type\": ["]
    #[doc = "        \"boolean\","]
    #[doc = "        \"null\""]
    #[doc = "      ]"]
    #[doc = "    },"]
    #[doc = "    \"issues\": {"]
    #[doc = "      \"description\": \"List of issues matching the query\","]
    #[doc = "      \"type\": \"array\","]
    #[doc = "      \"items\": {"]
    #[doc = "        \"$ref\": \"#/components/schemas/Issue\""]
    #[doc = "      }"]
    #[doc = "    },"]
    #[doc = "    \"nextPageToken\": {"]
    #[doc = "      \"description\": \"Token for fetching the next page of results (cursor-based pagination)\","]
    #[doc = "      \"type\": ["]
    #[doc = "        \"string\","]
    #[doc = "        \"null\""]
    #[doc = "      ]"]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
    pub struct SearchResponse {
        #[doc = "Whether this is the last page of results"]
        #[serde(
            rename = "isLast",
            default,
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub is_last: ::std::option::Option<bool>,
        #[doc = "List of issues matching the query"]
        pub issues: ::std::vec::Vec<Issue>,
        #[doc = "Token for fetching the next page of results (cursor-based pagination)"]
        #[serde(
            rename = "nextPageToken",
            default,
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub next_page_token: ::std::option::Option<::std::string::String>,
    }

    impl SearchResponse {
        pub fn builder() -> builder::SearchResponse {
            Default::default()
        }
    }

    #[doc = r" Types for composing complex structures."]
    pub mod builder {
        #[derive(Clone, Debug)]
        pub struct Error {
            error_code: ::std::result::Result<
                ::std::option::Option<::std::string::String>,
                ::std::string::String,
            >,
            message: ::std::result::Result<::std::string::String, ::std::string::String>,
            request_id: ::std::result::Result<::std::string::String, ::std::string::String>,
        }

        impl ::std::default::Default for Error {
            fn default() -> Self {
                Self {
                    error_code: Ok(Default::default()),
                    message: Err("no value supplied for message".to_string()),
                    request_id: Err("no value supplied for request_id".to_string()),
                }
            }
        }

        impl Error {
            pub fn error_code<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::option::Option<::std::string::String>>,
                T::Error: ::std::fmt::Display,
            {
                self.error_code = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for error_code: {e}"));
                self
            }
            pub fn message<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.message = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for message: {e}"));
                self
            }
            pub fn request_id<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.request_id = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for request_id: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<Error> for super::Error {
            type Error = super::error::ConversionError;
            fn try_from(
                value: Error,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    error_code: value.error_code?,
                    message: value.message?,
                    request_id: value.request_id?,
                })
            }
        }

        impl ::std::convert::From<super::Error> for Error {
            fn from(value: super::Error) -> Self {
                Self {
                    error_code: Ok(value.error_code),
                    message: Ok(value.message),
                    request_id: Ok(value.request_id),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct Issue {
            fields: ::std::result::Result<
                ::serde_json::Map<::std::string::String, ::serde_json::Value>,
                ::std::string::String,
            >,
            id: ::std::result::Result<::std::string::String, ::std::string::String>,
            key: ::std::result::Result<::std::string::String, ::std::string::String>,
            rendered_fields: ::std::result::Result<
                ::std::option::Option<
                    ::serde_json::Map<::std::string::String, ::serde_json::Value>,
                >,
                ::std::string::String,
            >,
        }

        impl ::std::default::Default for Issue {
            fn default() -> Self {
                Self {
                    fields: Err("no value supplied for fields".to_string()),
                    id: Err("no value supplied for id".to_string()),
                    key: Err("no value supplied for key".to_string()),
                    rendered_fields: Ok(Default::default()),
                }
            }
        }

        impl Issue {
            pub fn fields<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<
                    ::serde_json::Map<::std::string::String, ::serde_json::Value>,
                >,
                T::Error: ::std::fmt::Display,
            {
                self.fields = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for fields: {e}"));
                self
            }
            pub fn id<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.id = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for id: {e}"));
                self
            }
            pub fn key<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.key = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for key: {e}"));
                self
            }
            pub fn rendered_fields<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<
                    ::std::option::Option<
                        ::serde_json::Map<::std::string::String, ::serde_json::Value>,
                    >,
                >,
                T::Error: ::std::fmt::Display,
            {
                self.rendered_fields = value.try_into().map_err(|e| {
                    format!("error converting supplied value for rendered_fields: {e}")
                });
                self
            }
        }

        impl ::std::convert::TryFrom<Issue> for super::Issue {
            type Error = super::error::ConversionError;
            fn try_from(
                value: Issue,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    fields: value.fields?,
                    id: value.id?,
                    key: value.key?,
                    rendered_fields: value.rendered_fields?,
                })
            }
        }

        impl ::std::convert::From<super::Issue> for Issue {
            fn from(value: super::Issue) -> Self {
                Self {
                    fields: Ok(value.fields),
                    id: Ok(value.id),
                    key: Ok(value.key),
                    rendered_fields: Ok(value.rendered_fields),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct RemoteLink {
            id: ::std::result::Result<u64, ::std::string::String>,
            object: ::std::result::Result<
                ::std::option::Option<super::RemoteLinkObject>,
                ::std::string::String,
            >,
        }

        impl ::std::default::Default for RemoteLink {
            fn default() -> Self {
                Self {
                    id: Err("no value supplied for id".to_string()),
                    object: Ok(Default::default()),
                }
            }
        }

        impl RemoteLink {
            pub fn id<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<u64>,
                T::Error: ::std::fmt::Display,
            {
                self.id = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for id: {e}"));
                self
            }
            pub fn object<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::option::Option<super::RemoteLinkObject>>,
                T::Error: ::std::fmt::Display,
            {
                self.object = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for object: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<RemoteLink> for super::RemoteLink {
            type Error = super::error::ConversionError;
            fn try_from(
                value: RemoteLink,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    id: value.id?,
                    object: value.object?,
                })
            }
        }

        impl ::std::convert::From<super::RemoteLink> for RemoteLink {
            fn from(value: super::RemoteLink) -> Self {
                Self {
                    id: Ok(value.id),
                    object: Ok(value.object),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct RemoteLinkObject {
            title: ::std::result::Result<::std::string::String, ::std::string::String>,
            url: ::std::result::Result<::std::string::String, ::std::string::String>,
        }

        impl ::std::default::Default for RemoteLinkObject {
            fn default() -> Self {
                Self {
                    title: Err("no value supplied for title".to_string()),
                    url: Err("no value supplied for url".to_string()),
                }
            }
        }

        impl RemoteLinkObject {
            pub fn title<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.title = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for title: {e}"));
                self
            }
            pub fn url<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.url = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for url: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<RemoteLinkObject> for super::RemoteLinkObject {
            type Error = super::error::ConversionError;
            fn try_from(
                value: RemoteLinkObject,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    title: value.title?,
                    url: value.url?,
                })
            }
        }

        impl ::std::convert::From<super::RemoteLinkObject> for RemoteLinkObject {
            fn from(value: super::RemoteLinkObject) -> Self {
                Self {
                    title: Ok(value.title),
                    url: Ok(value.url),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct SearchResponse {
            is_last: ::std::result::Result<::std::option::Option<bool>, ::std::string::String>,
            issues: ::std::result::Result<::std::vec::Vec<super::Issue>, ::std::string::String>,
            next_page_token: ::std::result::Result<
                ::std::option::Option<::std::string::String>,
                ::std::string::String,
            >,
        }

        impl ::std::default::Default for SearchResponse {
            fn default() -> Self {
                Self {
                    is_last: Ok(Default::default()),
                    issues: Err("no value supplied for issues".to_string()),
                    next_page_token: Ok(Default::default()),
                }
            }
        }

        impl SearchResponse {
            pub fn is_last<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::option::Option<bool>>,
                T::Error: ::std::fmt::Display,
            {
                self.is_last = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for is_last: {e}"));
                self
            }
            pub fn issues<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::vec::Vec<super::Issue>>,
                T::Error: ::std::fmt::Display,
            {
                self.issues = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for issues: {e}"));
                self
            }
            pub fn next_page_token<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::option::Option<::std::string::String>>,
                T::Error: ::std::fmt::Display,
            {
                self.next_page_token = value.try_into().map_err(|e| {
                    format!("error converting supplied value for next_page_token: {e}")
                });
                self
            }
        }

        impl ::std::convert::TryFrom<SearchResponse> for super::SearchResponse {
            type Error = super::error::ConversionError;
            fn try_from(
                value: SearchResponse,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    is_last: value.is_last?,
                    issues: value.issues?,
                    next_page_token: value.next_page_token?,
                })
            }
        }

        impl ::std::convert::From<super::SearchResponse> for SearchResponse {
            fn from(value: super::SearchResponse) -> Self {
                Self {
                    is_last: Ok(value.is_last),
                    issues: Ok(value.issues),
                    next_page_token: Ok(value.next_page_token),
                }
            }
        }
    }
}

#[derive(Clone, Debug)]
#[doc = "Client for JIRA API (Subset)\n\nSubset of JIRA REST API v3 used by bugview-service. This is NOT a complete JIRA API - only the specific endpoints we consume.\n\nVersion: 0.1.0"]
pub struct Client {
    pub(crate) baseurl: String,
    pub(crate) client: reqwest::Client,
}

impl Client {
    #[doc = r" Create a new client."]
    #[doc = r""]
    #[doc = r" `baseurl` is the base URL provided to the internal"]
    #[doc = r" `reqwest::Client`, and should include a scheme and hostname,"]
    #[doc = r" as well as port and a path stem if applicable."]
    pub fn new(baseurl: &str) -> Self {
        #[cfg(not(target_arch = "wasm32"))]
        let client = {
            let dur = ::std::time::Duration::from_secs(15u64);
            reqwest::ClientBuilder::new()
                .connect_timeout(dur)
                .timeout(dur)
        };
        #[cfg(target_arch = "wasm32")]
        let client = reqwest::ClientBuilder::new();
        Self::new_with_client(baseurl, client.build().unwrap())
    }

    #[doc = r" Construct a new client with an existing `reqwest::Client`,"]
    #[doc = r" allowing more control over its configuration."]
    #[doc = r""]
    #[doc = r" `baseurl` is the base URL provided to the internal"]
    #[doc = r" `reqwest::Client`, and should include a scheme and hostname,"]
    #[doc = r" as well as port and a path stem if applicable."]
    pub fn new_with_client(baseurl: &str, client: reqwest::Client) -> Self {
        Self {
            baseurl: baseurl.to_string(),
            client,
        }
    }
}

impl ClientInfo<()> for Client {
    fn api_version() -> &'static str {
        "0.1.0"
    }

    fn baseurl(&self) -> &str {
        self.baseurl.as_str()
    }

    fn client(&self) -> &reqwest::Client {
        &self.client
    }

    fn inner(&self) -> &() {
        &()
    }
}

impl ClientHooks<()> for &Client {}
impl Client {
    #[doc = "Get a single issue by key\n\nRetrieves full details for a specific issue. Use the expand parameter to request additional data like renderedFields (HTML-rendered field values).\n\n**JIRA API Reference**: GET /rest/api/3/issue/{issueIdOrKey}\n\nSends a `GET` request to `/rest/api/3/issue/{issue_id_or_key}`\n\nArguments:\n- `issue_id_or_key`: Issue ID (some opaque number) or Key (e.g., \"PROJECT-123\")\n- `expand`: Comma-separated list of expansions (e.g., \"renderedFields\")\n```ignore\nlet response = client.get_issue()\n    .issue_id_or_key(issue_id_or_key)\n    .expand(expand)\n    .send()\n    .await;\n```"]
    pub fn get_issue(&self) -> builder::GetIssue<'_> {
        builder::GetIssue::new(self)
    }

    #[doc = "Get remote links for an issue\n\nRetrieves all remote links associated with an issue. Remote links are external URLs related to the issue.\n\n**JIRA API Reference**: GET /rest/api/3/issue/{issueIdOrKey}/remotelink\n\nSends a `GET` request to `/rest/api/3/issue/{issue_id_or_key}/remotelink`\n\nArguments:\n- `issue_id_or_key`: Issue ID (some opaque number) or Key (e.g., \"PROJECT-123\")\n```ignore\nlet response = client.get_remote_links()\n    .issue_id_or_key(issue_id_or_key)\n    .send()\n    .await;\n```"]
    pub fn get_remote_links(&self) -> builder::GetRemoteLinks<'_> {
        builder::GetRemoteLinks::new(self)
    }

    #[doc = "Search for issues using JQL\n\nSearches for issues using JIRA Query Language (JQL). Supports cursor-based pagination via the nextPageToken parameter.\n\n**JIRA API Reference**: GET /rest/api/3/search/jql\n\nSends a `GET` request to `/rest/api/3/search/jql`\n\nArguments:\n- `fields`: Comma-separated list of fields to include in the response\n- `jql`: JQL (JIRA Query Language) query string\n- `max_results`: Maximum number of results to return (default: 50)\n- `next_page_token`: Token for cursor-based pagination (returned from previous search)\n```ignore\nlet response = client.search_issues()\n    .fields(fields)\n    .jql(jql)\n    .max_results(max_results)\n    .next_page_token(next_page_token)\n    .send()\n    .await;\n```"]
    pub fn search_issues(&self) -> builder::SearchIssues<'_> {
        builder::SearchIssues::new(self)
    }
}

#[doc = r" Types for composing operation parameters."]
#[allow(clippy::all)]
pub mod builder {
    use super::types;
    #[allow(unused_imports)]
    use super::{
        encode_path, ByteStream, ClientHooks, ClientInfo, Error, OperationInfo, RequestBuilderExt,
        ResponseValue,
    };
    #[doc = "Builder for [`Client::get_issue`]\n\n[`Client::get_issue`]: super::Client::get_issue"]
    #[derive(Debug, Clone)]
    pub struct GetIssue<'a> {
        client: &'a super::Client,
        issue_id_or_key: Result<::std::string::String, String>,
        expand: Result<Option<::std::string::String>, String>,
    }

    impl<'a> GetIssue<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self {
                client: client,
                issue_id_or_key: Err("issue_id_or_key was not initialized".to_string()),
                expand: Ok(None),
            }
        }

        pub fn issue_id_or_key<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.issue_id_or_key = value.try_into().map_err(|_| {
                "conversion to `:: std :: string :: String` for issue_id_or_key failed".to_string()
            });
            self
        }

        pub fn expand<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.expand = value.try_into().map(Some).map_err(|_| {
                "conversion to `:: std :: string :: String` for expand failed".to_string()
            });
            self
        }

        #[doc = "Sends a `GET` request to `/rest/api/3/issue/{issue_id_or_key}`"]
        pub async fn send(self) -> Result<ResponseValue<types::Issue>, Error<types::Error>> {
            let Self {
                client,
                issue_id_or_key,
                expand,
            } = self;
            let issue_id_or_key = issue_id_or_key.map_err(Error::InvalidRequest)?;
            let expand = expand.map_err(Error::InvalidRequest)?;
            let url = format!(
                "{}/rest/api/3/issue/{}",
                client.baseurl,
                encode_path(&issue_id_or_key.to_string()),
            );
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .get(url)
                .header(
                    ::reqwest::header::ACCEPT,
                    ::reqwest::header::HeaderValue::from_static("application/json"),
                )
                .query(&progenitor_client::QueryParam::new("expand", &expand))
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "get_issue",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200u16 => ResponseValue::from_response(response).await,
                400u16..=499u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                500u16..=599u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                _ => Err(Error::UnexpectedResponse(response)),
            }
        }
    }

    #[doc = "Builder for [`Client::get_remote_links`]\n\n[`Client::get_remote_links`]: super::Client::get_remote_links"]
    #[derive(Debug, Clone)]
    pub struct GetRemoteLinks<'a> {
        client: &'a super::Client,
        issue_id_or_key: Result<::std::string::String, String>,
    }

    impl<'a> GetRemoteLinks<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self {
                client: client,
                issue_id_or_key: Err("issue_id_or_key was not initialized".to_string()),
            }
        }

        pub fn issue_id_or_key<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.issue_id_or_key = value.try_into().map_err(|_| {
                "conversion to `:: std :: string :: String` for issue_id_or_key failed".to_string()
            });
            self
        }

        #[doc = "Sends a `GET` request to `/rest/api/3/issue/{issue_id_or_key}/remotelink`"]
        pub async fn send(
            self,
        ) -> Result<ResponseValue<::std::vec::Vec<types::RemoteLink>>, Error<types::Error>>
        {
            let Self {
                client,
                issue_id_or_key,
            } = self;
            let issue_id_or_key = issue_id_or_key.map_err(Error::InvalidRequest)?;
            let url = format!(
                "{}/rest/api/3/issue/{}/remotelink",
                client.baseurl,
                encode_path(&issue_id_or_key.to_string()),
            );
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .get(url)
                .header(
                    ::reqwest::header::ACCEPT,
                    ::reqwest::header::HeaderValue::from_static("application/json"),
                )
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "get_remote_links",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200u16 => ResponseValue::from_response(response).await,
                400u16..=499u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                500u16..=599u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                _ => Err(Error::UnexpectedResponse(response)),
            }
        }
    }

    #[doc = "Builder for [`Client::search_issues`]\n\n[`Client::search_issues`]: super::Client::search_issues"]
    #[derive(Debug, Clone)]
    pub struct SearchIssues<'a> {
        client: &'a super::Client,
        fields: Result<Option<::std::string::String>, String>,
        jql: Result<::std::string::String, String>,
        max_results: Result<Option<u32>, String>,
        next_page_token: Result<Option<::std::string::String>, String>,
    }

    impl<'a> SearchIssues<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self {
                client: client,
                fields: Ok(None),
                jql: Err("jql was not initialized".to_string()),
                max_results: Ok(None),
                next_page_token: Ok(None),
            }
        }

        pub fn fields<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.fields = value.try_into().map(Some).map_err(|_| {
                "conversion to `:: std :: string :: String` for fields failed".to_string()
            });
            self
        }

        pub fn jql<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.jql = value.try_into().map_err(|_| {
                "conversion to `:: std :: string :: String` for jql failed".to_string()
            });
            self
        }

        pub fn max_results<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<u32>,
        {
            self.max_results = value
                .try_into()
                .map(Some)
                .map_err(|_| "conversion to `u32` for max_results failed".to_string());
            self
        }

        pub fn next_page_token<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<::std::string::String>,
        {
            self.next_page_token = value.try_into().map(Some).map_err(|_| {
                "conversion to `:: std :: string :: String` for next_page_token failed".to_string()
            });
            self
        }

        #[doc = "Sends a `GET` request to `/rest/api/3/search/jql`"]
        pub async fn send(
            self,
        ) -> Result<ResponseValue<types::SearchResponse>, Error<types::Error>> {
            let Self {
                client,
                fields,
                jql,
                max_results,
                next_page_token,
            } = self;
            let fields = fields.map_err(Error::InvalidRequest)?;
            let jql = jql.map_err(Error::InvalidRequest)?;
            let max_results = max_results.map_err(Error::InvalidRequest)?;
            let next_page_token = next_page_token.map_err(Error::InvalidRequest)?;
            let url = format!("{}/rest/api/3/search/jql", client.baseurl,);
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .get(url)
                .header(
                    ::reqwest::header::ACCEPT,
                    ::reqwest::header::HeaderValue::from_static("application/json"),
                )
                .query(&progenitor_client::QueryParam::new("fields", &fields))
                .query(&progenitor_client::QueryParam::new("jql", &jql))
                .query(&progenitor_client::QueryParam::new(
                    "maxResults",
                    &max_results,
                ))
                .query(&progenitor_client::QueryParam::new(
                    "nextPageToken",
                    &next_page_token,
                ))
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "search_issues",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200u16 => ResponseValue::from_response(response).await,
                400u16..=499u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                500u16..=599u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                _ => Err(Error::UnexpectedResponse(response)),
            }
        }
    }
}

#[doc = r" Items consumers will typically use such as the Client."]
pub mod prelude {
    pub use self::super::Client;
}
