// Generated by client-generator from openapi-specs/generated/cn-agent-api.json. Do not edit.

#[allow(unused_imports)]
pub use progenitor_client::{ByteStream, ClientInfo, Error, ResponseValue};
#[allow(unused_imports)]
use progenitor_client::{ClientHooks, OperationInfo, RequestBuilderExt, encode_path};
#[doc = r" Types used as operation parameters and responses."]
#[allow(clippy::all)]
pub mod types {
    #[doc = r" Error types."]
    pub mod error {
        #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
        pub struct ConversionError(::std::borrow::Cow<'static, str>);
        impl ::std::error::Error for ConversionError {}
        impl ::std::fmt::Display for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Display::fmt(&self.0, f)
            }
        }

        impl ::std::fmt::Debug for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }

        impl From<&'static str> for ConversionError {
            fn from(value: &'static str) -> Self {
                Self(value.into())
            }
        }

        impl From<String> for ConversionError {
            fn from(value: String) -> Self {
                Self(value.into())
            }
        }
    }

    #[doc = "Error information from a response."]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Error information from a response.\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"message\","]
    #[doc = "    \"request_id\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"error_code\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"message\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"request_id\": {"]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, schemars :: JsonSchema,
    )]
    pub struct Error {
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub error_code: ::std::option::Option<::std::string::String>,
        pub message: ::std::string::String,
        pub request_id: ::std::string::String,
    }

    impl Error {
        pub fn builder() -> builder::Error {
            Default::default()
        }
    }

    #[doc = "Health check response from `GET /ping`."]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Health check response from `GET /ping`.\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"backend\","]
    #[doc = "    \"name\","]
    #[doc = "    \"paused\","]
    #[doc = "    \"server_uuid\","]
    #[doc = "    \"version\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"backend\": {"]
    #[doc = "      \"description\": \"Backend name (e.g., \\\"smartos\\\", \\\"dummy\\\").\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"name\": {"]
    #[doc = "      \"description\": \"Agent name (e.g., \\\"cn-agent\\\").\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"paused\": {"]
    #[doc = "      \"description\": \"Whether the agent is currently paused (not accepting new tasks).\","]
    #[doc = "      \"type\": \"boolean\""]
    #[doc = "    },"]
    #[doc = "    \"server_uuid\": {"]
    #[doc = "      \"description\": \"Server UUID this agent is running on.\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"format\": \"uuid\""]
    #[doc = "    },"]
    #[doc = "    \"version\": {"]
    #[doc = "      \"description\": \"Agent version.\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, schemars :: JsonSchema,
    )]
    pub struct PingResponse {
        #[doc = "Backend name (e.g., \"smartos\", \"dummy\")."]
        pub backend: ::std::string::String,
        #[doc = "Agent name (e.g., \"cn-agent\")."]
        pub name: ::std::string::String,
        #[doc = "Whether the agent is currently paused (not accepting new tasks)."]
        pub paused: bool,
        #[doc = "Server UUID this agent is running on."]
        pub server_uuid: ::uuid::Uuid,
        #[doc = "Agent version."]
        pub version: ::std::string::String,
    }

    impl PingResponse {
        pub fn builder() -> builder::PingResponse {
            Default::default()
        }
    }

    #[doc = "A single entry in the task history ring buffer.\n\nThe legacy agent keeps the 16 most-recent tasks in memory. We preserve that behavior so operators relying on `curl /history` keep the same shape."]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"A single entry in the task history ring buffer.\\n\\nThe legacy agent keeps the 16 most-recent tasks in memory. We preserve that behavior so operators relying on `curl /history` keep the same shape.\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"params\","]
    #[doc = "    \"started_at\","]
    #[doc = "    \"status\","]
    #[doc = "    \"task\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"error_count\": {"]
    #[doc = "      \"description\": \"Number of error events emitted by the task (>0 implies failure).\","]
    #[doc = "      \"default\": 0,"]
    #[doc = "      \"type\": \"integer\","]
    #[doc = "      \"format\": \"uint32\","]
    #[doc = "      \"minimum\": 0.0"]
    #[doc = "    },"]
    #[doc = "    \"finished_at\": {"]
    #[doc = "      \"description\": \"ISO-8601 timestamp of when the task finished (absent if still running).\","]
    #[doc = "      \"type\": ["]
    #[doc = "        \"string\","]
    #[doc = "        \"null\""]
    #[doc = "      ]"]
    #[doc = "    },"]
    #[doc = "    \"params\": {"]
    #[doc = "      \"description\": \"Raw params the task was invoked with (may be redacted for `docker_build`).\""]
    #[doc = "    },"]
    #[doc = "    \"started_at\": {"]
    #[doc = "      \"description\": \"ISO-8601 timestamp of when the task started.\","]
    #[doc = "      \"type\": \"string\""]
    #[doc = "    },"]
    #[doc = "    \"status\": {"]
    #[doc = "      \"description\": \"Current status of the task (active, finished, failed).\","]
    #[doc = "      \"allOf\": ["]
    #[doc = "        {"]
    #[doc = "          \"$ref\": \"#/components/schemas/TaskStatus\""]
    #[doc = "        }"]
    #[doc = "      ]"]
    #[doc = "    },"]
    #[doc = "    \"task\": {"]
    #[doc = "      \"description\": \"The task that ran.\","]
    #[doc = "      \"allOf\": ["]
    #[doc = "        {"]
    #[doc = "          \"$ref\": \"#/components/schemas/TaskName\""]
    #[doc = "        }"]
    #[doc = "      ]"]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, schemars :: JsonSchema,
    )]
    pub struct TaskHistoryEntry {
        #[doc = "Number of error events emitted by the task (>0 implies failure)."]
        #[serde(default)]
        pub error_count: u32,
        #[doc = "ISO-8601 timestamp of when the task finished (absent if still running)."]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub finished_at: ::std::option::Option<::std::string::String>,
        #[doc = "Raw params the task was invoked with (may be redacted for `docker_build`)."]
        pub params: ::serde_json::Value,
        #[doc = "ISO-8601 timestamp of when the task started."]
        pub started_at: ::std::string::String,
        #[doc = "Current status of the task (active, finished, failed)."]
        pub status: TaskStatus,
        #[doc = "The task that ran."]
        pub task: TaskName,
    }

    impl TaskHistoryEntry {
        pub fn builder() -> builder::TaskHistoryEntry {
            Default::default()
        }
    }

    #[doc = "Response from `GET /history`."]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Response from `GET /history`.\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"entries\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"entries\": {"]
    #[doc = "      \"type\": \"array\","]
    #[doc = "      \"items\": {"]
    #[doc = "        \"$ref\": \"#/components/schemas/TaskHistoryEntry\""]
    #[doc = "      }"]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, schemars :: JsonSchema,
    )]
    pub struct TaskHistoryResponse {
        pub entries: ::std::vec::Vec<TaskHistoryEntry>,
    }

    impl TaskHistoryResponse {
        pub fn builder() -> builder::TaskHistoryResponse {
            Default::default()
        }
    }

    #[doc = "Canonical set of tasks the SmartOS backend of cn-agent can dispatch.\n\nEnum variants are serialized as the exact string names used in the legacy Node.js agent (see `lib/backends/smartos/index.js:queueDefns`). A catch-all `Unknown` variant lets newer CNAPIs send tasks an older agent does not yet understand without blowing up deserialization."]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Canonical set of tasks the SmartOS backend of cn-agent can dispatch.\\n\\nEnum variants are serialized as the exact string names used in the legacy Node.js agent (see `lib/backends/smartos/index.js:queueDefns`). A catch-all `Unknown` variant lets newer CNAPIs send tasks an older agent does not yet understand without blowing up deserialization.\","]
    #[doc = "  \"oneOf\": ["]
    #[doc = "    {"]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"enum\": ["]
    #[doc = "        \"machine_create\","]
    #[doc = "        \"machine_reprovision\","]
    #[doc = "        \"machine_destroy\","]
    #[doc = "        \"machine_boot\","]
    #[doc = "        \"machine_shutdown\","]
    #[doc = "        \"machine_reboot\","]
    #[doc = "        \"machine_kill\","]
    #[doc = "        \"machine_update\","]
    #[doc = "        \"machine_update_nics\","]
    #[doc = "        \"machine_screenshot\","]
    #[doc = "        \"machine_create_snapshot\","]
    #[doc = "        \"machine_delete_snapshot\","]
    #[doc = "        \"machine_rollback_snapshot\","]
    #[doc = "        \"machine_create_image\","]
    #[doc = "        \"machine_migrate\","]
    #[doc = "        \"machine_migrate_receive\","]
    #[doc = "        \"machine_load\","]
    #[doc = "        \"machine_info\","]
    #[doc = "        \"machine_proc\","]
    #[doc = "        \"image_ensure_present\","]
    #[doc = "        \"image_get\","]
    #[doc = "        \"server_sysinfo\","]
    #[doc = "        \"server_reboot\","]
    #[doc = "        \"server_update_nics\","]
    #[doc = "        \"server_overprovision_ratio\","]
    #[doc = "        \"command_execute\","]
    #[doc = "        \"recovery_config\","]
    #[doc = "        \"agent_install\","]
    #[doc = "        \"agents_uninstall\","]
    #[doc = "        \"refresh_agents\","]
    #[doc = "        \"shutdown_cn_agent_update\","]
    #[doc = "        \"docker_build\","]
    #[doc = "        \"docker_copy\","]
    #[doc = "        \"docker_exec\","]
    #[doc = "        \"docker_stats\","]
    #[doc = "        \"zfs_create_dataset\","]
    #[doc = "        \"zfs_destroy_dataset\","]
    #[doc = "        \"zfs_rename_dataset\","]
    #[doc = "        \"zfs_snapshot_dataset\","]
    #[doc = "        \"zfs_rollback_dataset\","]
    #[doc = "        \"zfs_clone_dataset\","]
    #[doc = "        \"zfs_set_properties\","]
    #[doc = "        \"zfs_get_properties\","]
    #[doc = "        \"zfs_list_datasets\","]
    #[doc = "        \"zfs_list_snapshots\","]
    #[doc = "        \"zfs_list_pools\","]
    #[doc = "        \"nop\","]
    #[doc = "        \"sleep\","]
    #[doc = "        \"test_subtask\""]
    #[doc = "      ]"]
    #[doc = "    },"]
    #[doc = "    {"]
    #[doc = "      \"description\": \"Catch-all for tasks this agent version does not understand. Dispatch will return an error explaining the task is unsupported.\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"enum\": ["]
    #[doc = "        \"unknown\""]
    #[doc = "      ]"]
    #[doc = "    }"]
    #[doc = "  ]"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize,
        :: serde :: Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
        clap :: ValueEnum,
        schemars :: JsonSchema,
    )]
    pub enum TaskName {
        #[serde(rename = "machine_create")]
        MachineCreate,
        #[serde(rename = "machine_reprovision")]
        MachineReprovision,
        #[serde(rename = "machine_destroy")]
        MachineDestroy,
        #[serde(rename = "machine_boot")]
        MachineBoot,
        #[serde(rename = "machine_shutdown")]
        MachineShutdown,
        #[serde(rename = "machine_reboot")]
        MachineReboot,
        #[serde(rename = "machine_kill")]
        MachineKill,
        #[serde(rename = "machine_update")]
        MachineUpdate,
        #[serde(rename = "machine_update_nics")]
        MachineUpdateNics,
        #[serde(rename = "machine_screenshot")]
        MachineScreenshot,
        #[serde(rename = "machine_create_snapshot")]
        MachineCreateSnapshot,
        #[serde(rename = "machine_delete_snapshot")]
        MachineDeleteSnapshot,
        #[serde(rename = "machine_rollback_snapshot")]
        MachineRollbackSnapshot,
        #[serde(rename = "machine_create_image")]
        MachineCreateImage,
        #[serde(rename = "machine_migrate")]
        MachineMigrate,
        #[serde(rename = "machine_migrate_receive")]
        MachineMigrateReceive,
        #[serde(rename = "machine_load")]
        MachineLoad,
        #[serde(rename = "machine_info")]
        MachineInfo,
        #[serde(rename = "machine_proc")]
        MachineProc,
        #[serde(rename = "image_ensure_present")]
        ImageEnsurePresent,
        #[serde(rename = "image_get")]
        ImageGet,
        #[serde(rename = "server_sysinfo")]
        ServerSysinfo,
        #[serde(rename = "server_reboot")]
        ServerReboot,
        #[serde(rename = "server_update_nics")]
        ServerUpdateNics,
        #[serde(rename = "server_overprovision_ratio")]
        ServerOverprovisionRatio,
        #[serde(rename = "command_execute")]
        CommandExecute,
        #[serde(rename = "recovery_config")]
        RecoveryConfig,
        #[serde(rename = "agent_install")]
        AgentInstall,
        #[serde(rename = "agents_uninstall")]
        AgentsUninstall,
        #[serde(rename = "refresh_agents")]
        RefreshAgents,
        #[serde(rename = "shutdown_cn_agent_update")]
        ShutdownCnAgentUpdate,
        #[serde(rename = "docker_build")]
        DockerBuild,
        #[serde(rename = "docker_copy")]
        DockerCopy,
        #[serde(rename = "docker_exec")]
        DockerExec,
        #[serde(rename = "docker_stats")]
        DockerStats,
        #[serde(rename = "zfs_create_dataset")]
        ZfsCreateDataset,
        #[serde(rename = "zfs_destroy_dataset")]
        ZfsDestroyDataset,
        #[serde(rename = "zfs_rename_dataset")]
        ZfsRenameDataset,
        #[serde(rename = "zfs_snapshot_dataset")]
        ZfsSnapshotDataset,
        #[serde(rename = "zfs_rollback_dataset")]
        ZfsRollbackDataset,
        #[serde(rename = "zfs_clone_dataset")]
        ZfsCloneDataset,
        #[serde(rename = "zfs_set_properties")]
        ZfsSetProperties,
        #[serde(rename = "zfs_get_properties")]
        ZfsGetProperties,
        #[serde(rename = "zfs_list_datasets")]
        ZfsListDatasets,
        #[serde(rename = "zfs_list_snapshots")]
        ZfsListSnapshots,
        #[serde(rename = "zfs_list_pools")]
        ZfsListPools,
        #[serde(rename = "nop")]
        Nop,
        #[serde(rename = "sleep")]
        Sleep,
        #[serde(rename = "test_subtask")]
        TestSubtask,
        #[doc = "Catch-all for tasks this agent version does not understand. Dispatch will return an error explaining the task is unsupported."]
        #[serde(rename = "unknown")]
        Unknown,
    }

    impl ::std::fmt::Display for TaskName {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::MachineCreate => f.write_str("machine_create"),
                Self::MachineReprovision => f.write_str("machine_reprovision"),
                Self::MachineDestroy => f.write_str("machine_destroy"),
                Self::MachineBoot => f.write_str("machine_boot"),
                Self::MachineShutdown => f.write_str("machine_shutdown"),
                Self::MachineReboot => f.write_str("machine_reboot"),
                Self::MachineKill => f.write_str("machine_kill"),
                Self::MachineUpdate => f.write_str("machine_update"),
                Self::MachineUpdateNics => f.write_str("machine_update_nics"),
                Self::MachineScreenshot => f.write_str("machine_screenshot"),
                Self::MachineCreateSnapshot => f.write_str("machine_create_snapshot"),
                Self::MachineDeleteSnapshot => f.write_str("machine_delete_snapshot"),
                Self::MachineRollbackSnapshot => f.write_str("machine_rollback_snapshot"),
                Self::MachineCreateImage => f.write_str("machine_create_image"),
                Self::MachineMigrate => f.write_str("machine_migrate"),
                Self::MachineMigrateReceive => f.write_str("machine_migrate_receive"),
                Self::MachineLoad => f.write_str("machine_load"),
                Self::MachineInfo => f.write_str("machine_info"),
                Self::MachineProc => f.write_str("machine_proc"),
                Self::ImageEnsurePresent => f.write_str("image_ensure_present"),
                Self::ImageGet => f.write_str("image_get"),
                Self::ServerSysinfo => f.write_str("server_sysinfo"),
                Self::ServerReboot => f.write_str("server_reboot"),
                Self::ServerUpdateNics => f.write_str("server_update_nics"),
                Self::ServerOverprovisionRatio => f.write_str("server_overprovision_ratio"),
                Self::CommandExecute => f.write_str("command_execute"),
                Self::RecoveryConfig => f.write_str("recovery_config"),
                Self::AgentInstall => f.write_str("agent_install"),
                Self::AgentsUninstall => f.write_str("agents_uninstall"),
                Self::RefreshAgents => f.write_str("refresh_agents"),
                Self::ShutdownCnAgentUpdate => f.write_str("shutdown_cn_agent_update"),
                Self::DockerBuild => f.write_str("docker_build"),
                Self::DockerCopy => f.write_str("docker_copy"),
                Self::DockerExec => f.write_str("docker_exec"),
                Self::DockerStats => f.write_str("docker_stats"),
                Self::ZfsCreateDataset => f.write_str("zfs_create_dataset"),
                Self::ZfsDestroyDataset => f.write_str("zfs_destroy_dataset"),
                Self::ZfsRenameDataset => f.write_str("zfs_rename_dataset"),
                Self::ZfsSnapshotDataset => f.write_str("zfs_snapshot_dataset"),
                Self::ZfsRollbackDataset => f.write_str("zfs_rollback_dataset"),
                Self::ZfsCloneDataset => f.write_str("zfs_clone_dataset"),
                Self::ZfsSetProperties => f.write_str("zfs_set_properties"),
                Self::ZfsGetProperties => f.write_str("zfs_get_properties"),
                Self::ZfsListDatasets => f.write_str("zfs_list_datasets"),
                Self::ZfsListSnapshots => f.write_str("zfs_list_snapshots"),
                Self::ZfsListPools => f.write_str("zfs_list_pools"),
                Self::Nop => f.write_str("nop"),
                Self::Sleep => f.write_str("sleep"),
                Self::TestSubtask => f.write_str("test_subtask"),
                Self::Unknown => f.write_str("unknown"),
            }
        }
    }

    impl ::std::str::FromStr for TaskName {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "machine_create" => Ok(Self::MachineCreate),
                "machine_reprovision" => Ok(Self::MachineReprovision),
                "machine_destroy" => Ok(Self::MachineDestroy),
                "machine_boot" => Ok(Self::MachineBoot),
                "machine_shutdown" => Ok(Self::MachineShutdown),
                "machine_reboot" => Ok(Self::MachineReboot),
                "machine_kill" => Ok(Self::MachineKill),
                "machine_update" => Ok(Self::MachineUpdate),
                "machine_update_nics" => Ok(Self::MachineUpdateNics),
                "machine_screenshot" => Ok(Self::MachineScreenshot),
                "machine_create_snapshot" => Ok(Self::MachineCreateSnapshot),
                "machine_delete_snapshot" => Ok(Self::MachineDeleteSnapshot),
                "machine_rollback_snapshot" => Ok(Self::MachineRollbackSnapshot),
                "machine_create_image" => Ok(Self::MachineCreateImage),
                "machine_migrate" => Ok(Self::MachineMigrate),
                "machine_migrate_receive" => Ok(Self::MachineMigrateReceive),
                "machine_load" => Ok(Self::MachineLoad),
                "machine_info" => Ok(Self::MachineInfo),
                "machine_proc" => Ok(Self::MachineProc),
                "image_ensure_present" => Ok(Self::ImageEnsurePresent),
                "image_get" => Ok(Self::ImageGet),
                "server_sysinfo" => Ok(Self::ServerSysinfo),
                "server_reboot" => Ok(Self::ServerReboot),
                "server_update_nics" => Ok(Self::ServerUpdateNics),
                "server_overprovision_ratio" => Ok(Self::ServerOverprovisionRatio),
                "command_execute" => Ok(Self::CommandExecute),
                "recovery_config" => Ok(Self::RecoveryConfig),
                "agent_install" => Ok(Self::AgentInstall),
                "agents_uninstall" => Ok(Self::AgentsUninstall),
                "refresh_agents" => Ok(Self::RefreshAgents),
                "shutdown_cn_agent_update" => Ok(Self::ShutdownCnAgentUpdate),
                "docker_build" => Ok(Self::DockerBuild),
                "docker_copy" => Ok(Self::DockerCopy),
                "docker_exec" => Ok(Self::DockerExec),
                "docker_stats" => Ok(Self::DockerStats),
                "zfs_create_dataset" => Ok(Self::ZfsCreateDataset),
                "zfs_destroy_dataset" => Ok(Self::ZfsDestroyDataset),
                "zfs_rename_dataset" => Ok(Self::ZfsRenameDataset),
                "zfs_snapshot_dataset" => Ok(Self::ZfsSnapshotDataset),
                "zfs_rollback_dataset" => Ok(Self::ZfsRollbackDataset),
                "zfs_clone_dataset" => Ok(Self::ZfsCloneDataset),
                "zfs_set_properties" => Ok(Self::ZfsSetProperties),
                "zfs_get_properties" => Ok(Self::ZfsGetProperties),
                "zfs_list_datasets" => Ok(Self::ZfsListDatasets),
                "zfs_list_snapshots" => Ok(Self::ZfsListSnapshots),
                "zfs_list_pools" => Ok(Self::ZfsListPools),
                "nop" => Ok(Self::Nop),
                "sleep" => Ok(Self::Sleep),
                "test_subtask" => Ok(Self::TestSubtask),
                "unknown" => Ok(Self::Unknown),
                _ => Err("invalid value".into()),
            }
        }
    }

    impl ::std::convert::TryFrom<&str> for TaskName {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }

    impl ::std::convert::TryFrom<&::std::string::String> for TaskName {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }

    impl ::std::convert::TryFrom<::std::string::String> for TaskName {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }

    #[doc = "Request body for `POST /tasks`.\n\nMatches the wire shape CNAPI sends today. `params` is deliberately untyped here; the service deserializes it into a task-specific struct after selecting a handler based on `task`."]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Request body for `POST /tasks`.\\n\\nMatches the wire shape CNAPI sends today. `params` is deliberately untyped here; the service deserializes it into a task-specific struct after selecting a handler based on `task`.\","]
    #[doc = "  \"type\": \"object\","]
    #[doc = "  \"required\": ["]
    #[doc = "    \"task\""]
    #[doc = "  ],"]
    #[doc = "  \"properties\": {"]
    #[doc = "    \"params\": {"]
    #[doc = "      \"description\": \"Arbitrary task-specific parameters.\""]
    #[doc = "    },"]
    #[doc = "    \"task\": {"]
    #[doc = "      \"description\": \"The task to execute.\","]
    #[doc = "      \"allOf\": ["]
    #[doc = "        {"]
    #[doc = "          \"$ref\": \"#/components/schemas/TaskName\""]
    #[doc = "        }"]
    #[doc = "      ]"]
    #[doc = "    }"]
    #[doc = "  }"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, schemars :: JsonSchema,
    )]
    pub struct TaskRequest {
        #[doc = "Arbitrary task-specific parameters."]
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub params: ::std::option::Option<::serde_json::Value>,
        #[doc = "The task to execute."]
        pub task: TaskName,
    }

    impl TaskRequest {
        pub fn builder() -> builder::TaskRequest {
            Default::default()
        }
    }

    #[doc = "Lifecycle state of a task."]
    #[doc = r""]
    #[doc = r" <details><summary>JSON schema</summary>"]
    #[doc = r""]
    #[doc = r" ```json"]
    #[doc = "{"]
    #[doc = "  \"description\": \"Lifecycle state of a task.\","]
    #[doc = "  \"oneOf\": ["]
    #[doc = "    {"]
    #[doc = "      \"description\": \"Task is currently running.\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"enum\": ["]
    #[doc = "        \"active\""]
    #[doc = "      ]"]
    #[doc = "    },"]
    #[doc = "    {"]
    #[doc = "      \"description\": \"Task finished successfully.\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"enum\": ["]
    #[doc = "        \"finished\""]
    #[doc = "      ]"]
    #[doc = "    },"]
    #[doc = "    {"]
    #[doc = "      \"description\": \"Task finished with an error.\","]
    #[doc = "      \"type\": \"string\","]
    #[doc = "      \"enum\": ["]
    #[doc = "        \"failed\""]
    #[doc = "      ]"]
    #[doc = "    }"]
    #[doc = "  ]"]
    #[doc = "}"]
    #[doc = r" ```"]
    #[doc = r" </details>"]
    #[derive(
        :: serde :: Deserialize,
        :: serde :: Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
        clap :: ValueEnum,
        schemars :: JsonSchema,
    )]
    pub enum TaskStatus {
        #[doc = "Task is currently running."]
        #[serde(rename = "active")]
        Active,
        #[doc = "Task finished successfully."]
        #[serde(rename = "finished")]
        Finished,
        #[doc = "Task finished with an error."]
        #[serde(rename = "failed")]
        Failed,
    }

    impl ::std::fmt::Display for TaskStatus {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Active => f.write_str("active"),
                Self::Finished => f.write_str("finished"),
                Self::Failed => f.write_str("failed"),
            }
        }
    }

    impl ::std::str::FromStr for TaskStatus {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "active" => Ok(Self::Active),
                "finished" => Ok(Self::Finished),
                "failed" => Ok(Self::Failed),
                _ => Err("invalid value".into()),
            }
        }
    }

    impl ::std::convert::TryFrom<&str> for TaskStatus {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }

    impl ::std::convert::TryFrom<&::std::string::String> for TaskStatus {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }

    impl ::std::convert::TryFrom<::std::string::String> for TaskStatus {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }

    #[doc = r" Types for composing complex structures."]
    pub mod builder {
        #[derive(Clone, Debug)]
        pub struct Error {
            error_code: ::std::result::Result<
                ::std::option::Option<::std::string::String>,
                ::std::string::String,
            >,
            message: ::std::result::Result<::std::string::String, ::std::string::String>,
            request_id: ::std::result::Result<::std::string::String, ::std::string::String>,
        }

        impl ::std::default::Default for Error {
            fn default() -> Self {
                Self {
                    error_code: Ok(Default::default()),
                    message: Err("no value supplied for message".to_string()),
                    request_id: Err("no value supplied for request_id".to_string()),
                }
            }
        }

        impl Error {
            pub fn error_code<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::option::Option<::std::string::String>>,
                T::Error: ::std::fmt::Display,
            {
                self.error_code = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for error_code: {e}"));
                self
            }
            pub fn message<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.message = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for message: {e}"));
                self
            }
            pub fn request_id<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.request_id = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for request_id: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<Error> for super::Error {
            type Error = super::error::ConversionError;
            fn try_from(
                value: Error,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    error_code: value.error_code?,
                    message: value.message?,
                    request_id: value.request_id?,
                })
            }
        }

        impl ::std::convert::From<super::Error> for Error {
            fn from(value: super::Error) -> Self {
                Self {
                    error_code: Ok(value.error_code),
                    message: Ok(value.message),
                    request_id: Ok(value.request_id),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct PingResponse {
            backend: ::std::result::Result<::std::string::String, ::std::string::String>,
            name: ::std::result::Result<::std::string::String, ::std::string::String>,
            paused: ::std::result::Result<bool, ::std::string::String>,
            server_uuid: ::std::result::Result<::uuid::Uuid, ::std::string::String>,
            version: ::std::result::Result<::std::string::String, ::std::string::String>,
        }

        impl ::std::default::Default for PingResponse {
            fn default() -> Self {
                Self {
                    backend: Err("no value supplied for backend".to_string()),
                    name: Err("no value supplied for name".to_string()),
                    paused: Err("no value supplied for paused".to_string()),
                    server_uuid: Err("no value supplied for server_uuid".to_string()),
                    version: Err("no value supplied for version".to_string()),
                }
            }
        }

        impl PingResponse {
            pub fn backend<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.backend = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for backend: {e}"));
                self
            }
            pub fn name<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.name = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for name: {e}"));
                self
            }
            pub fn paused<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<bool>,
                T::Error: ::std::fmt::Display,
            {
                self.paused = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for paused: {e}"));
                self
            }
            pub fn server_uuid<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::uuid::Uuid>,
                T::Error: ::std::fmt::Display,
            {
                self.server_uuid = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for server_uuid: {e}"));
                self
            }
            pub fn version<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.version = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for version: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<PingResponse> for super::PingResponse {
            type Error = super::error::ConversionError;
            fn try_from(
                value: PingResponse,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    backend: value.backend?,
                    name: value.name?,
                    paused: value.paused?,
                    server_uuid: value.server_uuid?,
                    version: value.version?,
                })
            }
        }

        impl ::std::convert::From<super::PingResponse> for PingResponse {
            fn from(value: super::PingResponse) -> Self {
                Self {
                    backend: Ok(value.backend),
                    name: Ok(value.name),
                    paused: Ok(value.paused),
                    server_uuid: Ok(value.server_uuid),
                    version: Ok(value.version),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct TaskHistoryEntry {
            error_count: ::std::result::Result<u32, ::std::string::String>,
            finished_at: ::std::result::Result<
                ::std::option::Option<::std::string::String>,
                ::std::string::String,
            >,
            params: ::std::result::Result<::serde_json::Value, ::std::string::String>,
            started_at: ::std::result::Result<::std::string::String, ::std::string::String>,
            status: ::std::result::Result<super::TaskStatus, ::std::string::String>,
            task: ::std::result::Result<super::TaskName, ::std::string::String>,
        }

        impl ::std::default::Default for TaskHistoryEntry {
            fn default() -> Self {
                Self {
                    error_count: Ok(Default::default()),
                    finished_at: Ok(Default::default()),
                    params: Err("no value supplied for params".to_string()),
                    started_at: Err("no value supplied for started_at".to_string()),
                    status: Err("no value supplied for status".to_string()),
                    task: Err("no value supplied for task".to_string()),
                }
            }
        }

        impl TaskHistoryEntry {
            pub fn error_count<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<u32>,
                T::Error: ::std::fmt::Display,
            {
                self.error_count = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for error_count: {e}"));
                self
            }
            pub fn finished_at<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::option::Option<::std::string::String>>,
                T::Error: ::std::fmt::Display,
            {
                self.finished_at = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for finished_at: {e}"));
                self
            }
            pub fn params<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::serde_json::Value>,
                T::Error: ::std::fmt::Display,
            {
                self.params = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for params: {e}"));
                self
            }
            pub fn started_at<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::string::String>,
                T::Error: ::std::fmt::Display,
            {
                self.started_at = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for started_at: {e}"));
                self
            }
            pub fn status<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<super::TaskStatus>,
                T::Error: ::std::fmt::Display,
            {
                self.status = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for status: {e}"));
                self
            }
            pub fn task<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<super::TaskName>,
                T::Error: ::std::fmt::Display,
            {
                self.task = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for task: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<TaskHistoryEntry> for super::TaskHistoryEntry {
            type Error = super::error::ConversionError;
            fn try_from(
                value: TaskHistoryEntry,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    error_count: value.error_count?,
                    finished_at: value.finished_at?,
                    params: value.params?,
                    started_at: value.started_at?,
                    status: value.status?,
                    task: value.task?,
                })
            }
        }

        impl ::std::convert::From<super::TaskHistoryEntry> for TaskHistoryEntry {
            fn from(value: super::TaskHistoryEntry) -> Self {
                Self {
                    error_count: Ok(value.error_count),
                    finished_at: Ok(value.finished_at),
                    params: Ok(value.params),
                    started_at: Ok(value.started_at),
                    status: Ok(value.status),
                    task: Ok(value.task),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct TaskHistoryResponse {
            entries: ::std::result::Result<
                ::std::vec::Vec<super::TaskHistoryEntry>,
                ::std::string::String,
            >,
        }

        impl ::std::default::Default for TaskHistoryResponse {
            fn default() -> Self {
                Self {
                    entries: Err("no value supplied for entries".to_string()),
                }
            }
        }

        impl TaskHistoryResponse {
            pub fn entries<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::vec::Vec<super::TaskHistoryEntry>>,
                T::Error: ::std::fmt::Display,
            {
                self.entries = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for entries: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<TaskHistoryResponse> for super::TaskHistoryResponse {
            type Error = super::error::ConversionError;
            fn try_from(
                value: TaskHistoryResponse,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    entries: value.entries?,
                })
            }
        }

        impl ::std::convert::From<super::TaskHistoryResponse> for TaskHistoryResponse {
            fn from(value: super::TaskHistoryResponse) -> Self {
                Self {
                    entries: Ok(value.entries),
                }
            }
        }

        #[derive(Clone, Debug)]
        pub struct TaskRequest {
            params: ::std::result::Result<
                ::std::option::Option<::serde_json::Value>,
                ::std::string::String,
            >,
            task: ::std::result::Result<super::TaskName, ::std::string::String>,
        }

        impl ::std::default::Default for TaskRequest {
            fn default() -> Self {
                Self {
                    params: Ok(Default::default()),
                    task: Err("no value supplied for task".to_string()),
                }
            }
        }

        impl TaskRequest {
            pub fn params<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<::std::option::Option<::serde_json::Value>>,
                T::Error: ::std::fmt::Display,
            {
                self.params = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for params: {e}"));
                self
            }
            pub fn task<T>(mut self, value: T) -> Self
            where
                T: ::std::convert::TryInto<super::TaskName>,
                T::Error: ::std::fmt::Display,
            {
                self.task = value
                    .try_into()
                    .map_err(|e| format!("error converting supplied value for task: {e}"));
                self
            }
        }

        impl ::std::convert::TryFrom<TaskRequest> for super::TaskRequest {
            type Error = super::error::ConversionError;
            fn try_from(
                value: TaskRequest,
            ) -> ::std::result::Result<Self, super::error::ConversionError> {
                Ok(Self {
                    params: value.params?,
                    task: value.task?,
                })
            }
        }

        impl ::std::convert::From<super::TaskRequest> for TaskRequest {
            fn from(value: super::TaskRequest) -> Self {
                Self {
                    params: Ok(value.params),
                    task: Ok(value.task),
                }
            }
        }
    }
}

#[derive(Clone, Debug)]
#[doc = "Client for Triton Compute Node Agent\n\nTriton cn-agent - per-compute-node HTTP agent that CNAPI dispatches VM lifecycle, ZFS, image, and agent-management tasks to\n\nVersion: 0.1.0"]
pub struct Client {
    pub(crate) baseurl: String,
    pub(crate) client: reqwest::Client,
}

impl Client {
    #[doc = r" Create a new client."]
    #[doc = r""]
    #[doc = r" `baseurl` is the base URL provided to the internal"]
    #[doc = r" `reqwest::Client`, and should include a scheme and hostname,"]
    #[doc = r" as well as port and a path stem if applicable."]
    pub fn new(baseurl: &str) -> Self {
        #[cfg(not(target_arch = "wasm32"))]
        let client = {
            let dur = ::std::time::Duration::from_secs(15u64);
            reqwest::ClientBuilder::new()
                .connect_timeout(dur)
                .timeout(dur)
        };
        #[cfg(target_arch = "wasm32")]
        let client = reqwest::ClientBuilder::new();
        Self::new_with_client(baseurl, client.build().unwrap())
    }

    #[doc = r" Construct a new client with an existing `reqwest::Client`,"]
    #[doc = r" allowing more control over its configuration."]
    #[doc = r""]
    #[doc = r" `baseurl` is the base URL provided to the internal"]
    #[doc = r" `reqwest::Client`, and should include a scheme and hostname,"]
    #[doc = r" as well as port and a path stem if applicable."]
    pub fn new_with_client(baseurl: &str, client: reqwest::Client) -> Self {
        Self {
            baseurl: baseurl.to_string(),
            client,
        }
    }
}

impl ClientInfo<()> for Client {
    fn api_version() -> &'static str {
        "0.1.0"
    }

    fn baseurl(&self) -> &str {
        self.baseurl.as_str()
    }

    fn client(&self) -> &reqwest::Client {
        &self.client
    }

    fn inner(&self) -> &() {
        &()
    }
}

impl ClientHooks<()> for &Client {}
impl Client {
    #[doc = "Return the in-memory task history (most recent first)\n\nSends a `GET` request to `/history`\n\n```ignore\nlet response = client.get_history()\n    .send()\n    .await;\n```"]
    pub fn get_history(&self) -> builder::GetHistory<'_> {
        builder::GetHistory::new(self)
    }

    #[doc = "Stop accepting new tasks\n\nPausing is used during agent self-update and CN reboots to drain work before the service exits. Tasks already in flight are not interrupted.\n\nSends a `POST` request to `/pause`\n\n```ignore\nlet response = client.pause()\n    .send()\n    .await;\n```"]
    pub fn pause(&self) -> builder::Pause<'_> {
        builder::Pause::new(self)
    }

    #[doc = "Health check and agent metadata\n\nSends a `GET` request to `/ping`\n\n```ignore\nlet response = client.ping()\n    .send()\n    .await;\n```"]
    pub fn ping(&self) -> builder::Ping<'_> {
        builder::Ping::new(self)
    }

    #[doc = "Resume accepting tasks after a prior pause\n\nSends a `POST` request to `/resume`\n\n```ignore\nlet response = client.resume()\n    .send()\n    .await;\n```"]
    pub fn resume(&self) -> builder::Resume<'_> {
        builder::Resume::new(self)
    }

    #[doc = "Dispatch a task\n\nRuns the named task with the given params. On success the task's result is returned as a JSON body; on failure a [`TaskError`] is returned with HTTP 500. If the agent is paused, returns HTTP 503.\n\nSends a `POST` request to `/tasks`\n\n```ignore\nlet response = client.dispatch_task()\n    .body(body)\n    .send()\n    .await;\n```"]
    pub fn dispatch_task(&self) -> builder::DispatchTask<'_> {
        builder::DispatchTask::new(self)
    }
}

#[doc = r" Types for composing operation parameters."]
#[allow(clippy::all)]
pub mod builder {
    use super::types;
    #[allow(unused_imports)]
    use super::{
        ByteStream, ClientHooks, ClientInfo, Error, OperationInfo, RequestBuilderExt,
        ResponseValue, encode_path,
    };
    #[doc = "Builder for [`Client::get_history`]\n\n[`Client::get_history`]: super::Client::get_history"]
    #[derive(Debug, Clone)]
    pub struct GetHistory<'a> {
        client: &'a super::Client,
    }

    impl<'a> GetHistory<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self { client: client }
        }

        #[doc = "Sends a `GET` request to `/history`"]
        pub async fn send(
            self,
        ) -> Result<ResponseValue<types::TaskHistoryResponse>, Error<types::Error>> {
            let Self { client } = self;
            let url = format!("{}/history", client.baseurl,);
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .get(url)
                .header(
                    ::reqwest::header::ACCEPT,
                    ::reqwest::header::HeaderValue::from_static("application/json"),
                )
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "get_history",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200u16 => ResponseValue::from_response(response).await,
                400u16..=499u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                500u16..=599u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                _ => Err(Error::UnexpectedResponse(response)),
            }
        }
    }

    #[doc = "Builder for [`Client::pause`]\n\n[`Client::pause`]: super::Client::pause"]
    #[derive(Debug, Clone)]
    pub struct Pause<'a> {
        client: &'a super::Client,
    }

    impl<'a> Pause<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self { client: client }
        }

        #[doc = "Sends a `POST` request to `/pause`"]
        pub async fn send(self) -> Result<ResponseValue<()>, Error<types::Error>> {
            let Self { client } = self;
            let url = format!("{}/pause", client.baseurl,);
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .post(url)
                .header(
                    ::reqwest::header::ACCEPT,
                    ::reqwest::header::HeaderValue::from_static("application/json"),
                )
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "pause",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                204u16 => Ok(ResponseValue::empty(response)),
                400u16..=499u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                500u16..=599u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                _ => Err(Error::UnexpectedResponse(response)),
            }
        }
    }

    #[doc = "Builder for [`Client::ping`]\n\n[`Client::ping`]: super::Client::ping"]
    #[derive(Debug, Clone)]
    pub struct Ping<'a> {
        client: &'a super::Client,
    }

    impl<'a> Ping<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self { client: client }
        }

        #[doc = "Sends a `GET` request to `/ping`"]
        pub async fn send(self) -> Result<ResponseValue<types::PingResponse>, Error<types::Error>> {
            let Self { client } = self;
            let url = format!("{}/ping", client.baseurl,);
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .get(url)
                .header(
                    ::reqwest::header::ACCEPT,
                    ::reqwest::header::HeaderValue::from_static("application/json"),
                )
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "ping",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200u16 => ResponseValue::from_response(response).await,
                400u16..=499u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                500u16..=599u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                _ => Err(Error::UnexpectedResponse(response)),
            }
        }
    }

    #[doc = "Builder for [`Client::resume`]\n\n[`Client::resume`]: super::Client::resume"]
    #[derive(Debug, Clone)]
    pub struct Resume<'a> {
        client: &'a super::Client,
    }

    impl<'a> Resume<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self { client: client }
        }

        #[doc = "Sends a `POST` request to `/resume`"]
        pub async fn send(self) -> Result<ResponseValue<()>, Error<types::Error>> {
            let Self { client } = self;
            let url = format!("{}/resume", client.baseurl,);
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .post(url)
                .header(
                    ::reqwest::header::ACCEPT,
                    ::reqwest::header::HeaderValue::from_static("application/json"),
                )
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "resume",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                204u16 => Ok(ResponseValue::empty(response)),
                400u16..=499u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                500u16..=599u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                _ => Err(Error::UnexpectedResponse(response)),
            }
        }
    }

    #[doc = "Builder for [`Client::dispatch_task`]\n\n[`Client::dispatch_task`]: super::Client::dispatch_task"]
    #[derive(Debug, Clone)]
    pub struct DispatchTask<'a> {
        client: &'a super::Client,
        body: Result<types::builder::TaskRequest, String>,
    }

    impl<'a> DispatchTask<'a> {
        pub fn new(client: &'a super::Client) -> Self {
            Self {
                client: client,
                body: Ok(::std::default::Default::default()),
            }
        }

        pub fn body<V>(mut self, value: V) -> Self
        where
            V: std::convert::TryInto<types::TaskRequest>,
            <V as std::convert::TryInto<types::TaskRequest>>::Error: std::fmt::Display,
        {
            self.body = value
                .try_into()
                .map(From::from)
                .map_err(|s| format!("conversion to `TaskRequest` for body failed: {}", s));
            self
        }

        pub fn body_map<F>(mut self, f: F) -> Self
        where
            F: std::ops::FnOnce(types::builder::TaskRequest) -> types::builder::TaskRequest,
        {
            self.body = self.body.map(f);
            self
        }

        #[doc = "Sends a `POST` request to `/tasks`"]
        pub async fn send(self) -> Result<ResponseValue<::serde_json::Value>, Error<types::Error>> {
            let Self { client, body } = self;
            let body = body
                .and_then(|v| types::TaskRequest::try_from(v).map_err(|e| e.to_string()))
                .map_err(Error::InvalidRequest)?;
            let url = format!("{}/tasks", client.baseurl,);
            let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
            header_map.append(
                ::reqwest::header::HeaderName::from_static("api-version"),
                ::reqwest::header::HeaderValue::from_static(super::Client::api_version()),
            );
            #[allow(unused_mut)]
            let mut request = client
                .client
                .post(url)
                .header(
                    ::reqwest::header::ACCEPT,
                    ::reqwest::header::HeaderValue::from_static("application/json"),
                )
                .json(&body)
                .headers(header_map)
                .build()?;
            let info = OperationInfo {
                operation_id: "dispatch_task",
            };
            client.pre(&mut request, &info).await?;
            let result = client.exec(request, &info).await;
            client.post(&result, &info).await?;
            let response = result?;
            match response.status().as_u16() {
                200u16 => ResponseValue::from_response(response).await,
                400u16..=499u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                500u16..=599u16 => Err(Error::ErrorResponse(
                    ResponseValue::from_response(response).await?,
                )),
                _ => Err(Error::UnexpectedResponse(response)),
            }
        }
    }
}

#[doc = r" Items consumers will typically use such as the Client."]
pub mod prelude {
    pub use self::super::Client;
}
