// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright 2026 Edgecast Cloud LLC.

//! Per-CN "console ticket" — a short-lived HS256 JWT that authorises a
//! single console attach.
//!
//! ## Why this exists
//!
//! Serial / VNC console access fans out as
//! `browser → admin-backend → tritond → tritonagent → guest console`.
//! The last hop dials a small HTTPS+WebSocket listener that the agent
//! runs on the CN admin IP. That listener needs to know the request
//! really came from tritond and is scoped to one VM — it must not be
//! a generic "open any console" door.
//!
//! tritond mints a ticket bound to `(server_uuid, vm_uuid, kind)` with
//! a ~30 s expiry; the agent verifies the signature with the key it
//! was issued at registration, then checks the three claims against
//! the request path / query before upgrading the socket. A leaked
//! ticket cannot be replayed against another VM, another CN, or to
//! flip `serial`↔`vnc`, and it dies in seconds.
//!
//! ## Key separation
//!
//! Each CN gets its **own** [`ConsoleTicketKey`], generated by tritond
//! when it approves the CN (alongside the per-CN API key) and returned
//! to the agent in the registration response. Per-CN keying means a
//! single compromised CN can mint tickets that only *its own* listener
//! will accept — and a compromised agent already controls its zones.
//! It is deliberately **not** the operator-login [`crate::JwtKey`]:
//! handing that to every CN would let any CN forge operator access
//! tokens.

use chrono::Utc;
use jsonwebtoken::{Algorithm, DecodingKey, EncodingKey, Header, Validation};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use zeroize::Zeroize;

/// HS256 key length, in bytes. 32 bytes (256 bits) matches the hash
/// block size and the convention used by [`crate::JwtKey`] and
/// [`crate::IdentityHmacKey`].
pub const CONSOLE_TICKET_KEY_BYTES: usize = 32;

/// Default ticket lifetime. Long enough to cover a slow proxy
/// hand-off, short enough that a captured ticket is near-useless.
pub const DEFAULT_TICKET_TTL_SECS: i64 = 30;

/// Which console a ticket authorises. Serialises as `serial` / `vnc`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum ConsoleKind {
    /// Text console: zoneadmd zone console (bhyve / native / lx) or the
    /// KVM serial UDS.
    Serial,
    /// Graphical framebuffer (RFB / VNC). Only valid for bhyve and KVM.
    Vnc,
}

impl ConsoleKind {
    /// Stable lowercase wire name (`"serial"` / `"vnc"`).
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            ConsoleKind::Serial => "serial",
            ConsoleKind::Vnc => "vnc",
        }
    }
}

impl std::fmt::Display for ConsoleKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Errors returned by [`ConsoleTicketKey::verify`].
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
#[non_exhaustive]
pub enum ConsoleTicketError {
    /// Signature did not verify, the token was malformed, or it
    /// expired. We deliberately collapse these into one variant so a
    /// verifier can't be used as an oracle to distinguish "expired"
    /// from "forged".
    #[error("invalid console ticket")]
    Invalid,

    /// Signature + expiry were fine, but a bound claim
    /// (`cn` / `vm` / `kind`) did not match what the caller asked us
    /// to check.
    #[error("console ticket scope mismatch")]
    ScopeMismatch,
}

/// JWT claims carried by a console ticket.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct TicketClaims {
    /// Compute node (`server_uuid`) the ticket is valid on.
    cn: Uuid,
    /// VM / zone UUID the ticket authorises.
    vm: Uuid,
    /// Console kind.
    kind: ConsoleKind,
    /// Expiry, unix seconds. Validated by `jsonwebtoken`.
    exp: i64,
    /// Issued-at, unix seconds.
    iat: i64,
}

/// Per-CN HS256 signing / verifying key for console tickets.
///
/// Wraps the raw bytes plus the derived `jsonwebtoken` keys. `Drop`
/// zeroes the raw bytes; the `EncodingKey` / `DecodingKey` keep their
/// own copies that `jsonwebtoken` does not expose a destructor for —
/// the same residual-bytes caveat as [`crate::JwtKey`].
pub struct ConsoleTicketKey {
    encoding: EncodingKey,
    decoding: DecodingKey,
    bytes: [u8; CONSOLE_TICKET_KEY_BYTES],
}

impl ConsoleTicketKey {
    /// Generate a fresh random key. tritond calls this once per CN at
    /// approval time and persists [`Self::bytes`] on the CN record.
    #[must_use = "the generated key is the only copy of this credential"]
    pub fn generate() -> Self {
        use rand::RngCore;
        let mut bytes = [0u8; CONSOLE_TICKET_KEY_BYTES];
        rand::rng().fill_bytes(&mut bytes);
        Self::from_bytes(bytes)
    }

    /// Reconstruct from previously-persisted bytes (tritond from the CN
    /// record; the agent from its on-disk credential file).
    #[must_use]
    pub fn from_bytes(bytes: [u8; CONSOLE_TICKET_KEY_BYTES]) -> Self {
        Self {
            encoding: EncodingKey::from_secret(&bytes),
            decoding: DecodingKey::from_secret(&bytes),
            bytes,
        }
    }

    /// Borrow the raw key bytes (for persistence / transport at
    /// registration). Caller is responsible for not logging them.
    #[must_use]
    pub fn bytes(&self) -> &[u8; CONSOLE_TICKET_KEY_BYTES] {
        &self.bytes
    }

    /// Mint a ticket valid for `ttl_secs` seconds bound to
    /// `(server_uuid, vm_uuid, kind)`.
    ///
    /// Returns [`ConsoleTicketError::Invalid`] only on a JWT-encode
    /// failure, which is unreachable for this fixed claim shape but is
    /// surfaced rather than panicking (the workspace bans `expect`).
    pub fn mint(
        &self,
        server_uuid: Uuid,
        vm_uuid: Uuid,
        kind: ConsoleKind,
        ttl_secs: i64,
    ) -> Result<String, ConsoleTicketError> {
        let now = Utc::now().timestamp();
        let claims = TicketClaims {
            cn: server_uuid,
            vm: vm_uuid,
            kind,
            iat: now,
            exp: now + ttl_secs.max(1),
        };
        jsonwebtoken::encode(&Header::new(Algorithm::HS256), &claims, &self.encoding)
            .map_err(|_| ConsoleTicketError::Invalid)
    }

    /// Verify a ticket: signature, expiry, then the bound scope.
    ///
    /// Returns `Ok(())` only if the token verifies *and* its `cn`,
    /// `vm`, and `kind` claims equal the supplied values.
    pub fn verify(
        &self,
        token: &str,
        expect_server_uuid: Uuid,
        expect_vm_uuid: Uuid,
        expect_kind: ConsoleKind,
    ) -> Result<(), ConsoleTicketError> {
        let mut validation = Validation::new(Algorithm::HS256);
        // We do our own audience-equivalent check on `cn`; the `aud`
        // claim isn't used, so don't let jsonwebtoken require it.
        validation.validate_aud = false;
        validation.set_required_spec_claims(&["exp"]);
        // Tickets live ~30 s; the default 60 s leeway would more than
        // double that. Allow only a few seconds of clock skew between
        // tritond (minter) and the agent (verifier).
        validation.leeway = 5;
        let data = jsonwebtoken::decode::<TicketClaims>(token, &self.decoding, &validation)
            .map_err(|_| ConsoleTicketError::Invalid)?;
        let c = data.claims;
        if c.cn != expect_server_uuid || c.vm != expect_vm_uuid || c.kind != expect_kind {
            return Err(ConsoleTicketError::ScopeMismatch);
        }
        Ok(())
    }
}

impl Drop for ConsoleTicketKey {
    fn drop(&mut self) {
        self.bytes.zeroize();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn uuids() -> (Uuid, Uuid) {
        (
            Uuid::parse_str("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa").unwrap(),
            Uuid::parse_str("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb").unwrap(),
        )
    }

    #[test]
    fn mint_verify_round_trip() {
        let key = ConsoleTicketKey::generate();
        let (cn, vm) = uuids();
        let t = key
            .mint(cn, vm, ConsoleKind::Serial, DEFAULT_TICKET_TTL_SECS)
            .unwrap();
        assert_eq!(key.verify(&t, cn, vm, ConsoleKind::Serial), Ok(()));
    }

    #[test]
    fn rejects_wrong_cn() {
        let key = ConsoleTicketKey::generate();
        let (cn, vm) = uuids();
        let other = Uuid::parse_str("99999999-9999-9999-9999-999999999999").unwrap();
        let t = key
            .mint(cn, vm, ConsoleKind::Serial, DEFAULT_TICKET_TTL_SECS)
            .unwrap();
        assert_eq!(
            key.verify(&t, other, vm, ConsoleKind::Serial),
            Err(ConsoleTicketError::ScopeMismatch)
        );
    }

    #[test]
    fn rejects_wrong_vm() {
        let key = ConsoleTicketKey::generate();
        let (cn, vm) = uuids();
        let other = Uuid::parse_str("99999999-9999-9999-9999-999999999999").unwrap();
        let t = key
            .mint(cn, vm, ConsoleKind::Vnc, DEFAULT_TICKET_TTL_SECS)
            .unwrap();
        assert_eq!(
            key.verify(&t, cn, other, ConsoleKind::Vnc),
            Err(ConsoleTicketError::ScopeMismatch)
        );
    }

    #[test]
    fn rejects_wrong_kind() {
        let key = ConsoleTicketKey::generate();
        let (cn, vm) = uuids();
        let t = key
            .mint(cn, vm, ConsoleKind::Serial, DEFAULT_TICKET_TTL_SECS)
            .unwrap();
        assert_eq!(
            key.verify(&t, cn, vm, ConsoleKind::Vnc),
            Err(ConsoleTicketError::ScopeMismatch)
        );
    }

    #[test]
    fn rejects_wrong_key() {
        let a = ConsoleTicketKey::from_bytes([1u8; CONSOLE_TICKET_KEY_BYTES]);
        let b = ConsoleTicketKey::from_bytes([2u8; CONSOLE_TICKET_KEY_BYTES]);
        let (cn, vm) = uuids();
        let t = a
            .mint(cn, vm, ConsoleKind::Serial, DEFAULT_TICKET_TTL_SECS)
            .unwrap();
        assert_eq!(
            b.verify(&t, cn, vm, ConsoleKind::Serial),
            Err(ConsoleTicketError::Invalid)
        );
    }

    #[test]
    fn rejects_expired() {
        let key = ConsoleTicketKey::generate();
        let (cn, vm) = uuids();
        let now = Utc::now().timestamp();
        let claims = TicketClaims {
            cn,
            vm,
            kind: ConsoleKind::Serial,
            iat: now - 360,
            exp: now - 300,
        };
        let token = jsonwebtoken::encode(
            &Header::new(Algorithm::HS256),
            &claims,
            &EncodingKey::from_secret(key.bytes()),
        )
        .unwrap();
        assert_eq!(
            key.verify(&token, cn, vm, ConsoleKind::Serial),
            Err(ConsoleTicketError::Invalid)
        );
    }

    #[test]
    fn rejects_garbage() {
        let key = ConsoleTicketKey::generate();
        let (cn, vm) = uuids();
        assert_eq!(
            key.verify("", cn, vm, ConsoleKind::Serial),
            Err(ConsoleTicketError::Invalid)
        );
        assert_eq!(
            key.verify("not.a.jwt", cn, vm, ConsoleKind::Serial),
            Err(ConsoleTicketError::Invalid)
        );
    }

    #[test]
    fn from_bytes_round_trips() {
        let bytes = [0x42u8; CONSOLE_TICKET_KEY_BYTES];
        let key = ConsoleTicketKey::from_bytes(bytes);
        assert_eq!(key.bytes(), &bytes);
    }

    #[test]
    fn console_kind_wire_names() {
        assert_eq!(
            serde_json::to_string(&ConsoleKind::Serial).unwrap(),
            "\"serial\""
        );
        assert_eq!(serde_json::to_string(&ConsoleKind::Vnc).unwrap(), "\"vnc\"");
        assert_eq!(ConsoleKind::Serial.as_str(), "serial");
        assert_eq!(ConsoleKind::Vnc.to_string(), "vnc");
    }
}
