// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright 2026 Edgecast Cloud LLC.

//! Per-CN IMDSv2 session token -- a short-lived HS256 JWT a guest
//! obtains via `PUT /latest/api/token` and must present on every
//! subsequent GET/PUT to the local IMDS daemon
//! (`tritonagent/src/imds.rs`).
//!
//! ## Why this exists
//!
//! `IMDS_DESIGN.md` (rev 4) ships **IMDSv2-only** — there is no
//! token-less GET path. A guest process:
//!
//! 1. `PUT /latest/api/token` with `X-aws-ec2-metadata-token-ttl-seconds`.
//! 2. Gets back an opaque token; the listener forces the response IP
//!    TTL down to the realized `triton/config/imds/hop-limit` (default
//!    1) so a misconfigured forwarding proxy can't relay the token
//!    off-box.
//! 3. Includes it as `X-aws-ec2-metadata-token: <tok>` on every
//!    subsequent `GET /latest/...` / `GET /triton/...` /
//!    `PUT /triton/guest/...`.
//!
//! The daemon binds the token to **the connection's derived identity**
//! (the proteus per-port NAT mapping → `port_id` → `instance_id`),
//! not anything the guest sends. A token leaked into another VM is
//! useless there because the verifier checks the request's identity
//! against the claims.
//!
//! ## Key separation
//!
//! Each CN gets its own [`ImdsTokenKey`], generated by tritond at CN
//! approval time and delivered to the agent in the registration
//! response (same shape as [`crate::ConsoleTicketKey`]). Per-CN keying
//! means a compromised CN can mint tokens that only its own listener
//! will accept; the operator-login `JwtKey` is **not** reused.

use chrono::Utc;
use jsonwebtoken::{Algorithm, DecodingKey, EncodingKey, Header, Validation};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use zeroize::Zeroize;

/// HS256 key length, in bytes. Matches [`crate::ConsoleTicketKey`] and
/// [`crate::JwtKey`] so the per-CN persistence story is uniform.
pub const IMDS_TOKEN_KEY_BYTES: usize = 32;

/// Lower bound on the `X-aws-ec2-metadata-token-ttl-seconds` header
/// (matches AWS). A guest asking for a TTL smaller than this gets
/// clamped up to `MIN`; a guest asking for more than `MAX` gets
/// clamped down. The daemon does the clamping; this module just
/// honours whatever ttl is requested.
pub const IMDS_TOKEN_TTL_MIN_SECS: i64 = 1;
/// Upper bound on the requested TTL (AWS uses 21600 = 6h).
pub const IMDS_TOKEN_TTL_MAX_SECS: i64 = 21_600;
/// Conventional default when the guest omits the TTL header (AWS uses
/// 21600 but defaults can vary; the IMDS daemon picks its own when
/// the header is missing -- this constant is just the value the rest
/// of the codebase reaches for).
pub const IMDS_TOKEN_TTL_DEFAULT_SECS: i64 = 21_600;

/// Errors returned by [`ImdsTokenKey::verify`].
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
#[non_exhaustive]
pub enum ImdsTokenError {
    /// Signature did not verify, the token was malformed, or it
    /// expired. Collapsed into one variant so verifiers can't be
    /// used as an oracle.
    #[error("invalid IMDS token")]
    Invalid,

    /// Signature + expiry were fine, but a bound claim
    /// (`port` / `instance`) did not match the request's derived
    /// identity. A leaked token is useless on a different virtual
    /// wire.
    #[error("IMDS token scope mismatch")]
    ScopeMismatch,
}

/// JWT claims carried by an IMDSv2 session token.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct TokenClaims {
    /// proteus per-port UUID the token is valid for.
    port: Uuid,
    /// Instance UUID the port belongs to. Redundant with `port` (the
    /// agent maintains the mapping) but carried so the verifier can
    /// cross-check the two without a round trip.
    instance: Uuid,
    /// Expiry, unix seconds. Validated by `jsonwebtoken`.
    exp: i64,
    /// Issued-at, unix seconds.
    iat: i64,
}

/// Per-CN HS256 signing / verifying key for IMDSv2 session tokens.
/// Same residual-bytes caveat as [`crate::ConsoleTicketKey`]:
/// `jsonwebtoken`'s `EncodingKey` / `DecodingKey` keep their own
/// copies that aren't zeroed on drop; the raw `bytes` field is.
pub struct ImdsTokenKey {
    encoding: EncodingKey,
    decoding: DecodingKey,
    bytes: [u8; IMDS_TOKEN_KEY_BYTES],
}

impl ImdsTokenKey {
    /// Generate a fresh random key. tritond calls this once per CN at
    /// approval time and persists [`Self::bytes`] on the CN record.
    #[must_use = "the generated key is the only copy of this credential"]
    pub fn generate() -> Self {
        use rand::RngCore;
        let mut bytes = [0u8; IMDS_TOKEN_KEY_BYTES];
        rand::rng().fill_bytes(&mut bytes);
        Self::from_bytes(bytes)
    }

    /// Reconstruct from previously-persisted bytes.
    #[must_use]
    pub fn from_bytes(bytes: [u8; IMDS_TOKEN_KEY_BYTES]) -> Self {
        Self {
            encoding: EncodingKey::from_secret(&bytes),
            decoding: DecodingKey::from_secret(&bytes),
            bytes,
        }
    }

    /// Borrow the raw key bytes (for persistence / transport).
    #[must_use]
    pub fn bytes(&self) -> &[u8; IMDS_TOKEN_KEY_BYTES] {
        &self.bytes
    }

    /// Mint a token valid for `ttl_secs` seconds bound to
    /// `(port_id, instance_id)`. The caller is expected to clamp
    /// `ttl_secs` to `[IMDS_TOKEN_TTL_MIN_SECS, IMDS_TOKEN_TTL_MAX_SECS]`
    /// before calling.
    pub fn mint(
        &self,
        port_id: Uuid,
        instance_id: Uuid,
        ttl_secs: i64,
    ) -> Result<String, ImdsTokenError> {
        let now = Utc::now().timestamp();
        let claims = TokenClaims {
            port: port_id,
            instance: instance_id,
            iat: now,
            exp: now + ttl_secs.max(IMDS_TOKEN_TTL_MIN_SECS),
        };
        jsonwebtoken::encode(&Header::new(Algorithm::HS256), &claims, &self.encoding)
            .map_err(|_| ImdsTokenError::Invalid)
    }

    /// Verify a token: signature, expiry, then the bound scope. The
    /// `expect_port_id` is the proteus port the connection arrived
    /// on; `expect_instance_id` is its blueprint-recorded owner. A
    /// token replayed on another VM fails `ScopeMismatch` here.
    pub fn verify(
        &self,
        token: &str,
        expect_port_id: Uuid,
        expect_instance_id: Uuid,
    ) -> Result<(), ImdsTokenError> {
        let mut validation = Validation::new(Algorithm::HS256);
        validation.validate_aud = false;
        validation.set_required_spec_claims(&["exp"]);
        // Tokens live up to 6h but are usually short; allow only a
        // few seconds of clock skew between tritond (mint path is
        // theoretically possible) and the agent (the usual minter).
        validation.leeway = 5;
        let data = jsonwebtoken::decode::<TokenClaims>(token, &self.decoding, &validation)
            .map_err(|_| ImdsTokenError::Invalid)?;
        let c = data.claims;
        if c.port != expect_port_id || c.instance != expect_instance_id {
            return Err(ImdsTokenError::ScopeMismatch);
        }
        Ok(())
    }
}

impl Drop for ImdsTokenKey {
    fn drop(&mut self) {
        self.bytes.zeroize();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn uuids() -> (Uuid, Uuid) {
        (
            Uuid::parse_str("11111111-1111-1111-1111-111111111111").unwrap(),
            Uuid::parse_str("22222222-2222-2222-2222-222222222222").unwrap(),
        )
    }

    #[test]
    fn mint_verify_round_trip() {
        let key = ImdsTokenKey::generate();
        let (port, instance) = uuids();
        let t = key.mint(port, instance, 300).unwrap();
        assert_eq!(key.verify(&t, port, instance), Ok(()));
    }

    #[test]
    fn rejects_wrong_port() {
        let key = ImdsTokenKey::generate();
        let (port, instance) = uuids();
        let other = Uuid::parse_str("99999999-9999-9999-9999-999999999999").unwrap();
        let t = key.mint(port, instance, 300).unwrap();
        assert_eq!(
            key.verify(&t, other, instance),
            Err(ImdsTokenError::ScopeMismatch)
        );
    }

    #[test]
    fn rejects_wrong_instance() {
        let key = ImdsTokenKey::generate();
        let (port, instance) = uuids();
        let other = Uuid::parse_str("99999999-9999-9999-9999-999999999999").unwrap();
        let t = key.mint(port, instance, 300).unwrap();
        assert_eq!(
            key.verify(&t, port, other),
            Err(ImdsTokenError::ScopeMismatch)
        );
    }

    #[test]
    fn cross_key_rejection() {
        let a = ImdsTokenKey::generate();
        let b = ImdsTokenKey::generate();
        let (port, instance) = uuids();
        let t = a.mint(port, instance, 300).unwrap();
        assert_eq!(b.verify(&t, port, instance), Err(ImdsTokenError::Invalid));
    }

    #[test]
    fn from_bytes_round_trip() {
        let bytes = [7u8; IMDS_TOKEN_KEY_BYTES];
        let a = ImdsTokenKey::from_bytes(bytes);
        let b = ImdsTokenKey::from_bytes(*a.bytes());
        let (port, instance) = uuids();
        let t = a.mint(port, instance, 300).unwrap();
        assert_eq!(b.verify(&t, port, instance), Ok(()));
    }
}
