// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright 2026 Edgecast Cloud LLC.

//! Per-CN "migration ticket" — a short-lived HS256 JWT that authorises
//! one CN-to-CN live-migration WebSocket attach.
//!
//! ## Why this exists (vs. [`crate::ConsoleTicketKey`])
//!
//! Live VM migration fans out as
//! `source-CN tritonagent → target-CN tritonagent` over a direct
//! WebSocket on the CN admin IP (plan §D, port 4568). The target's
//! listener needs to know the request really came from a tritond-
//! authorized migration and is scoped to a specific record.
//!
//! tritond mints **two** tickets per migration:
//!
//! * one carrying `role=outbound`, handed to the source agent — the
//!   source presents it in its `Authorization: Bearer …` header when
//!   dialing the target's listener.
//! * one carrying `role=inbound`, written into the target's
//!   `MigrationRecord` so its listener knows which migration the
//!   inbound dial is fulfilling.
//!
//! Both bind `(source_cn, target_cn, vm_uuid, migration_id, role)` and
//! die in 10 minutes — long enough to cover a slow saga step, short
//! enough that a leaked ticket can't be replayed against a future
//! migration. The migration_id binding means a captured ticket cannot
//! be re-used for a different migration of the same VM either.
//!
//! ## Key separation
//!
//! Each CN gets its **own** [`MigrateTicketKey`], generated by tritond
//! when it approves the CN (alongside the per-CN API key + console
//! ticket key) and returned to the agent in the registration
//! response. The migration listener verifies tickets against the
//! key its own CN was issued — so a compromised CN can mint tickets
//! that only its own listener accepts.
//!
//! Specifically not reused: the [`ConsoleTicketKey`] (different
//! scope semantics — a console ticket binds a single
//! `(cn, vm, kind)`, never carries a role) and the operator-login
//! [`crate::JwtKey`] (handing that to every CN would let any CN
//! forge operator access tokens).

use chrono::Utc;
use jsonwebtoken::{Algorithm, DecodingKey, EncodingKey, Header, Validation};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use zeroize::Zeroize;

/// HS256 key length, in bytes. 32 bytes (256 bits) matches the hash
/// block size and the convention used by [`crate::ConsoleTicketKey`].
pub const MIGRATE_TICKET_KEY_BYTES: usize = 32;

/// Default ticket lifetime. 10 minutes — long enough to cover a slow
/// saga step (full RAM push for a large VM can take minutes), short
/// enough that a captured ticket isn't a serious threat. Plan §D.2.
pub const DEFAULT_MIGRATE_TICKET_TTL_SECS: i64 = 600;

/// Whether a ticket authorises the source-side dial or the
/// target-side accept. Wire form is lowercase
/// (`outbound` / `inbound`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum MigrateRole {
    /// Source side — presented by the dialer when connecting.
    Outbound,
    /// Target side — held by the listener; identifies which
    /// migration an inbound connection is fulfilling.
    Inbound,
}

impl MigrateRole {
    /// Stable lowercase wire name (`"outbound"` / `"inbound"`).
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            MigrateRole::Outbound => "outbound",
            MigrateRole::Inbound => "inbound",
        }
    }
}

impl std::fmt::Display for MigrateRole {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Errors returned by [`MigrateTicketKey::verify`].
///
/// We deliberately collapse signature failure / malformed token /
/// expired into a single [`Self::Invalid`] variant so a verifier
/// can't be used as an oracle to distinguish "expired" from "forged".
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
#[non_exhaustive]
pub enum MigrateTicketError {
    /// Signature did not verify, the token was malformed, or it
    /// expired.
    #[error("invalid migrate ticket")]
    Invalid,

    /// Signature + expiry were fine, but a bound claim (source CN /
    /// target CN / vm / migration_id / role) did not match what the
    /// caller asked us to check.
    #[error("migrate ticket scope mismatch")]
    ScopeMismatch,
}

/// JWT claims carried by a migrate ticket.
///
/// The five binding claims plus `iat`/`exp` are everything a
/// verifier needs. The two CN claims are split (`scn` / `tcn`) so
/// the listener can reject a target-bound ticket that lies about
/// either end — handy for the cutover audit log.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct TicketClaims {
    /// Source CN (`server_uuid`).
    scn: Uuid,
    /// Target CN (`server_uuid`).
    tcn: Uuid,
    /// VM / zone UUID the migration moves.
    vm: Uuid,
    /// Migration record id this ticket is scoped to.
    mig: Uuid,
    /// Which side of the migration this ticket authorises.
    role: MigrateRole,
    /// Expiry, unix seconds. Validated by `jsonwebtoken`.
    exp: i64,
    /// Issued-at, unix seconds.
    iat: i64,
}

/// Per-CN HS256 signing / verifying key for migration tickets.
///
/// Wraps the raw bytes plus the derived `jsonwebtoken` keys. `Drop`
/// zeroes the raw bytes; the `EncodingKey` / `DecodingKey` keep
/// their own copies that `jsonwebtoken` does not expose a destructor
/// for — the same residual-bytes caveat as
/// [`crate::ConsoleTicketKey`] / [`crate::JwtKey`].
pub struct MigrateTicketKey {
    encoding: EncodingKey,
    decoding: DecodingKey,
    bytes: [u8; MIGRATE_TICKET_KEY_BYTES],
}

impl MigrateTicketKey {
    /// Generate a fresh random key. tritond calls this once per CN at
    /// approval time and persists [`Self::bytes`] on the CN record
    /// (alongside the existing per-CN API key + console ticket key).
    #[must_use = "the generated key is the only copy of this credential"]
    pub fn generate() -> Self {
        use rand::RngCore;
        let mut bytes = [0u8; MIGRATE_TICKET_KEY_BYTES];
        rand::rng().fill_bytes(&mut bytes);
        Self::from_bytes(bytes)
    }

    /// Reconstruct from previously-persisted bytes (tritond from the
    /// CN record; the agent from its on-disk credential file).
    #[must_use]
    pub fn from_bytes(bytes: [u8; MIGRATE_TICKET_KEY_BYTES]) -> Self {
        Self {
            encoding: EncodingKey::from_secret(&bytes),
            decoding: DecodingKey::from_secret(&bytes),
            bytes,
        }
    }

    /// Borrow the raw key bytes (for persistence / transport at
    /// registration). Caller is responsible for not logging them.
    #[must_use]
    pub fn bytes(&self) -> &[u8; MIGRATE_TICKET_KEY_BYTES] {
        &self.bytes
    }

    /// Mint a ticket valid for `ttl_secs` seconds bound to
    /// `(source_cn, target_cn, vm_uuid, migration_id, role)`.
    ///
    /// Returns [`MigrateTicketError::Invalid`] only on a JWT-encode
    /// failure, which is unreachable for this fixed claim shape but
    /// is surfaced rather than panicking (the workspace bans
    /// `expect`).
    pub fn mint(
        &self,
        source_cn: Uuid,
        target_cn: Uuid,
        vm_uuid: Uuid,
        migration_id: Uuid,
        role: MigrateRole,
        ttl_secs: i64,
    ) -> Result<String, MigrateTicketError> {
        let now = Utc::now().timestamp();
        let claims = TicketClaims {
            scn: source_cn,
            tcn: target_cn,
            vm: vm_uuid,
            mig: migration_id,
            role,
            iat: now,
            exp: now + ttl_secs.max(1),
        };
        jsonwebtoken::encode(&Header::new(Algorithm::HS256), &claims, &self.encoding)
            .map_err(|_| MigrateTicketError::Invalid)
    }

    /// Verify a ticket: signature, expiry, then the bound scope.
    ///
    /// Returns `Ok(())` only if the token verifies *and* all five
    /// bound claims equal the supplied values.
    pub fn verify(
        &self,
        token: &str,
        expect_source_cn: Uuid,
        expect_target_cn: Uuid,
        expect_vm_uuid: Uuid,
        expect_migration_id: Uuid,
        expect_role: MigrateRole,
    ) -> Result<(), MigrateTicketError> {
        let mut validation = Validation::new(Algorithm::HS256);
        validation.validate_aud = false;
        validation.set_required_spec_claims(&["exp"]);
        // Tickets live ~10 min; allow only a few seconds of clock
        // skew between tritond (minter) and the agent (verifier).
        validation.leeway = 5;
        let data = jsonwebtoken::decode::<TicketClaims>(token, &self.decoding, &validation)
            .map_err(|_| MigrateTicketError::Invalid)?;
        let c = data.claims;
        if c.scn != expect_source_cn
            || c.tcn != expect_target_cn
            || c.vm != expect_vm_uuid
            || c.mig != expect_migration_id
            || c.role != expect_role
        {
            return Err(MigrateTicketError::ScopeMismatch);
        }
        Ok(())
    }
}

impl Drop for MigrateTicketKey {
    fn drop(&mut self) {
        self.bytes.zeroize();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn quad() -> (Uuid, Uuid, Uuid, Uuid) {
        (
            Uuid::parse_str("11111111-1111-1111-1111-111111111111").unwrap(),
            Uuid::parse_str("22222222-2222-2222-2222-222222222222").unwrap(),
            Uuid::parse_str("33333333-3333-3333-3333-333333333333").unwrap(),
            Uuid::parse_str("44444444-4444-4444-4444-444444444444").unwrap(),
        )
    }

    #[test]
    fn mint_verify_round_trip_outbound() {
        let key = MigrateTicketKey::generate();
        let (scn, tcn, vm, mig) = quad();
        let t = key
            .mint(
                scn,
                tcn,
                vm,
                mig,
                MigrateRole::Outbound,
                DEFAULT_MIGRATE_TICKET_TTL_SECS,
            )
            .unwrap();
        assert_eq!(
            key.verify(&t, scn, tcn, vm, mig, MigrateRole::Outbound),
            Ok(())
        );
    }

    #[test]
    fn mint_verify_round_trip_inbound() {
        let key = MigrateTicketKey::generate();
        let (scn, tcn, vm, mig) = quad();
        let t = key
            .mint(
                scn,
                tcn,
                vm,
                mig,
                MigrateRole::Inbound,
                DEFAULT_MIGRATE_TICKET_TTL_SECS,
            )
            .unwrap();
        assert_eq!(
            key.verify(&t, scn, tcn, vm, mig, MigrateRole::Inbound),
            Ok(())
        );
    }

    #[test]
    fn rejects_wrong_source_cn() {
        let key = MigrateTicketKey::generate();
        let (scn, tcn, vm, mig) = quad();
        let other = Uuid::parse_str("99999999-9999-9999-9999-999999999999").unwrap();
        let t = key
            .mint(
                scn,
                tcn,
                vm,
                mig,
                MigrateRole::Outbound,
                DEFAULT_MIGRATE_TICKET_TTL_SECS,
            )
            .unwrap();
        assert_eq!(
            key.verify(&t, other, tcn, vm, mig, MigrateRole::Outbound),
            Err(MigrateTicketError::ScopeMismatch)
        );
    }

    #[test]
    fn rejects_wrong_target_cn() {
        let key = MigrateTicketKey::generate();
        let (scn, tcn, vm, mig) = quad();
        let other = Uuid::parse_str("99999999-9999-9999-9999-999999999999").unwrap();
        let t = key
            .mint(
                scn,
                tcn,
                vm,
                mig,
                MigrateRole::Outbound,
                DEFAULT_MIGRATE_TICKET_TTL_SECS,
            )
            .unwrap();
        assert_eq!(
            key.verify(&t, scn, other, vm, mig, MigrateRole::Outbound),
            Err(MigrateTicketError::ScopeMismatch)
        );
    }

    #[test]
    fn rejects_wrong_vm() {
        let key = MigrateTicketKey::generate();
        let (scn, tcn, vm, mig) = quad();
        let other = Uuid::parse_str("99999999-9999-9999-9999-999999999999").unwrap();
        let t = key
            .mint(
                scn,
                tcn,
                vm,
                mig,
                MigrateRole::Inbound,
                DEFAULT_MIGRATE_TICKET_TTL_SECS,
            )
            .unwrap();
        assert_eq!(
            key.verify(&t, scn, tcn, other, mig, MigrateRole::Inbound),
            Err(MigrateTicketError::ScopeMismatch)
        );
    }

    #[test]
    fn rejects_wrong_migration_id() {
        let key = MigrateTicketKey::generate();
        let (scn, tcn, vm, mig) = quad();
        let other = Uuid::parse_str("99999999-9999-9999-9999-999999999999").unwrap();
        let t = key
            .mint(
                scn,
                tcn,
                vm,
                mig,
                MigrateRole::Outbound,
                DEFAULT_MIGRATE_TICKET_TTL_SECS,
            )
            .unwrap();
        assert_eq!(
            key.verify(&t, scn, tcn, vm, other, MigrateRole::Outbound),
            Err(MigrateTicketError::ScopeMismatch)
        );
    }

    #[test]
    fn rejects_wrong_role() {
        let key = MigrateTicketKey::generate();
        let (scn, tcn, vm, mig) = quad();
        let t = key
            .mint(
                scn,
                tcn,
                vm,
                mig,
                MigrateRole::Outbound,
                DEFAULT_MIGRATE_TICKET_TTL_SECS,
            )
            .unwrap();
        assert_eq!(
            key.verify(&t, scn, tcn, vm, mig, MigrateRole::Inbound),
            Err(MigrateTicketError::ScopeMismatch)
        );
    }

    #[test]
    fn rejects_wrong_key() {
        let a = MigrateTicketKey::from_bytes([1u8; MIGRATE_TICKET_KEY_BYTES]);
        let b = MigrateTicketKey::from_bytes([2u8; MIGRATE_TICKET_KEY_BYTES]);
        let (scn, tcn, vm, mig) = quad();
        let t = a
            .mint(
                scn,
                tcn,
                vm,
                mig,
                MigrateRole::Outbound,
                DEFAULT_MIGRATE_TICKET_TTL_SECS,
            )
            .unwrap();
        assert_eq!(
            b.verify(&t, scn, tcn, vm, mig, MigrateRole::Outbound),
            Err(MigrateTicketError::Invalid)
        );
    }

    #[test]
    fn rejects_expired() {
        let key = MigrateTicketKey::generate();
        let (scn, tcn, vm, mig) = quad();
        let now = Utc::now().timestamp();
        let claims = TicketClaims {
            scn,
            tcn,
            vm,
            mig,
            role: MigrateRole::Outbound,
            iat: now - 7200,
            exp: now - 3600,
        };
        let token = jsonwebtoken::encode(
            &Header::new(Algorithm::HS256),
            &claims,
            &EncodingKey::from_secret(key.bytes()),
        )
        .unwrap();
        assert_eq!(
            key.verify(&token, scn, tcn, vm, mig, MigrateRole::Outbound),
            Err(MigrateTicketError::Invalid)
        );
    }

    #[test]
    fn rejects_garbage() {
        let key = MigrateTicketKey::generate();
        let (scn, tcn, vm, mig) = quad();
        assert_eq!(
            key.verify("", scn, tcn, vm, mig, MigrateRole::Outbound),
            Err(MigrateTicketError::Invalid)
        );
        assert_eq!(
            key.verify("not.a.jwt", scn, tcn, vm, mig, MigrateRole::Outbound),
            Err(MigrateTicketError::Invalid)
        );
    }

    #[test]
    fn from_bytes_round_trips() {
        let bytes = [0x42u8; MIGRATE_TICKET_KEY_BYTES];
        let key = MigrateTicketKey::from_bytes(bytes);
        assert_eq!(key.bytes(), &bytes);
    }

    #[test]
    fn migrate_role_wire_names() {
        assert_eq!(
            serde_json::to_string(&MigrateRole::Outbound).unwrap(),
            "\"outbound\""
        );
        assert_eq!(
            serde_json::to_string(&MigrateRole::Inbound).unwrap(),
            "\"inbound\""
        );
        assert_eq!(MigrateRole::Outbound.as_str(), "outbound");
        assert_eq!(MigrateRole::Inbound.to_string(), "inbound");
    }
}
