// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright 2026 Edgecast Cloud LLC.

//! Catalog of registered sagas.
//!
//! Every multi-resource operation that touches more than one FDB
//! resource, or that enqueues work for any `tritonagent`, runs as a
//! saga registered here (RFD 00004 D-Sg-3). The catalog is also the
//! documented design surface: a module that doesn't exist is a gap;
//! an action without an undo is a leak waiting to happen.
//!
//! ## Modules
//!
//! * [`instance_create`] — replaces the imperative body of
//!   `create_project_instance` (`handlers/instances.rs:116`).
//!   Chains: create the instance + NIC/IP/disk allocations + pin
//!   the host CN + persist the autogenerated root password →
//!   enqueue a `Provision` job → wait for the agent to ack the job
//!   terminal. Unwind tail enqueues a `Delete` job and tears the
//!   record down so a failure leaves nothing leaked.
//!
//! SG-3 / SG-5 / SG-6 add the rest of the catalog
//! (`instance_delete`, `floating_ip_*`, `nat_gateway_*`,
//! `node_join`, `image_import`).
//!
//! ## Registration
//!
//! [`register_all_actions`] is the one function the
//! `SagaExecutor` builder calls. It walks every catalog module and
//! calls its `register(reg)` to populate the
//! [`tritond_saga::ActionRegistry`].

use tritond_saga::ActionRegistry;

pub mod instance_create;

/// Register every catalog action and version stamp onto the given
/// registry. Called once at server-start before the
/// [`tritond_saga::SagaExecutor`] is built.
///
/// SG-2 ships only `instance-create`; subsequent slices register
/// more modules here.
pub fn register_all_actions(reg: &mut ActionRegistry) {
    instance_create::register(reg);
}

/// `(name, version)` pairs for every saga registered above. The
/// executor walks this list at build time so `recover_all_for_sec`
/// can reject sagas whose persisted version is no longer in the
/// registry (RFD 00004 D-Sg-10).
pub fn registered_versions() -> Vec<(&'static str, u32)> {
    vec![(instance_create::SAGA_NAME, instance_create::SAGA_VERSION)]
}
