// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright 2026 Edgecast Cloud LLC.

//! Catalog of registered sagas.
//!
//! Every multi-resource operation that touches more than one FDB
//! resource, or that enqueues work for any `tritonagent`, runs as a
//! saga registered here. The catalog is also the
//! documented design surface: a module that doesn't exist is a gap;
//! an action without an undo is a leak waiting to happen.
//!
//! ## Modules
//!
//! * [`instance_create`] — replaces the imperative body of
//!   `create_project_instance` (`handlers/instances.rs:116`).
//!   Chains: create the instance + NIC/IP/disk allocations + pin
//!   the host CN + persist the autogenerated root password →
//!   enqueue a `Provision` job → wait for the agent to ack the job
//!   terminal. Unwind tail enqueues a `Delete` job and tears the
//!   record down so a failure leaves nothing leaked.
//!
//! SG-3 / SG-5 / SG-6 add the rest of the catalog
//! (`instance_delete`, `floating_ip_*`, `nat_gateway_*`,
//! `node_join`, `image_import`).
//!
//! ## Registration
//!
//! [`register_all_actions`] is the one function the
//! `SagaExecutor` builder calls. It walks every catalog module and
//! calls its `register(reg)` to populate the
//! [`tritond_saga::ActionRegistry`].

use std::future::Future;
use std::time::Duration;

use tritond_saga::{ActionError, ActionRegistry};

pub mod common;
pub mod designate;
pub mod floating_ip;
pub mod image_import;
pub mod instance_create;
pub mod instance_delete;
pub mod instance_lifecycle;
pub mod migration;
pub mod nat_gateway;
pub mod node_join;

/// Per-action timeout so a wedged agent/store/external call surfaces
/// as a structured `ActionError` instead of hanging the saga. The
/// error payload lets unwind paths distinguish timeout from other
/// failure modes.
pub async fn with_action_timeout<T>(
    action: &'static str,
    duration: Duration,
    fut: impl Future<Output = Result<T, ActionError>>,
) -> Result<T, ActionError> {
    match tokio::time::timeout(duration, fut).await {
        Ok(result) => result,
        Err(_) => Err(ActionError::action_failed(serde_json::json!({
            "kind": "action_timeout",
            "action": action,
            "duration_secs": duration.as_secs(),
        }))),
    }
}

/// Register every catalog action and version stamp onto the given
/// registry. Called once at server-start before the
/// [`tritond_saga::SagaExecutor`] is built.
///
/// SG-2 ships only `instance-create`; subsequent slices register
/// more modules here.
pub fn register_all_actions(reg: &mut ActionRegistry) {
    designate::register(reg);
    instance_create::register(reg);
    instance_delete::register(reg);
    instance_lifecycle::register(reg);
    floating_ip::register(reg);
    migration::register(reg);
    nat_gateway::register(reg);
    node_join::register(reg);
    image_import::register(reg);
}

/// `(name, version)` pairs for every saga registered above. The
/// executor walks this list at build time so `recover_all_for_sec`
/// can reject sagas whose persisted version is no longer in the
/// registry.
pub fn registered_versions() -> Vec<(&'static str, u32)> {
    vec![
        (
            designate::STANDALONE_SAGA_NAME,
            designate::STANDALONE_SAGA_VERSION,
        ),
        (instance_create::SAGA_NAME, instance_create::SAGA_VERSION),
        (instance_delete::SAGA_NAME, instance_delete::SAGA_VERSION),
        (
            instance_lifecycle::SAGA_NAME_START,
            instance_lifecycle::SAGA_VERSION,
        ),
        (
            instance_lifecycle::SAGA_NAME_STOP,
            instance_lifecycle::SAGA_VERSION,
        ),
        (
            instance_lifecycle::SAGA_NAME_RESTART,
            instance_lifecycle::SAGA_VERSION,
        ),
        (floating_ip::SAGA_NAME_ALLOCATE, floating_ip::SAGA_VERSION),
        (floating_ip::SAGA_NAME_ATTACH, floating_ip::SAGA_VERSION),
        (floating_ip::SAGA_NAME_DETACH, floating_ip::SAGA_VERSION),
        (nat_gateway::SAGA_NAME_CREATE, nat_gateway::SAGA_VERSION),
        (nat_gateway::SAGA_NAME_DELETE, nat_gateway::SAGA_VERSION),
        (node_join::SAGA_NAME, node_join::SAGA_VERSION),
        (image_import::SAGA_NAME, image_import::SAGA_VERSION),
        (migration::SAGA_NAME, migration::SAGA_VERSION),
    ]
}
